### ISSUE TITLE
New term request: Lymphoblast

### ISSUE THREAD

**Issue by kalpanaps** [obophenotype/cell-ontology#1103]

**Comment by kalpanaps** [comment]
has brenda BTO:0000772

**Comment by lubianat** [comment]
@kalpanaps Hello, can you provide a bit more info on the term? I will create it based on http://purl.obolibrary.org/obo/FMA_83030 otherwise as an xref

**Comment by addiehl** [comment]
Not a fan of this term because it is used to describe activated lymphocytes including both normal and leukemia cell types, but if we have to have it I would like to see it defined as follows (per [NCIT C13013](https://ncit.nci.nih.gov/ncitbrowser/ConceptReport.jsp?dictionary=NCI_Thesaurus&version=21.06e&ns=ncit&code=C13013)):  "A lymphocyte that has gotten larger after being stimulated by an antigen."

The parent is 'lymphocyte', of course.

Note that this definition is the first part of the NCI-Gloss Definition, not the NCI definition. As a lapsed immunologist, I consider this a better definition because both immature and mature lymphocytes will adopt the blast morphology upon stimulation.  The second part of the NCI-Gloss Definition should not be included.

We should also include a comment that this term does not refer to leukemia cell types, as it is a type of native cell, not abnormal cell.

possible equivalence axiom
lymphocyte and 
 'bearer of' some 'increased size' and
 'output of' some 'lymphocyte activation'

Alex

**Comment by kalpanaps** [comment]
Hi Tiago,

Thank you for considering my request:)

I would like to define lymphoblast as an immature lymphocyte that has enlarged in response to antigenic stimulation.

Other database cross-references are,

SNOMEDCT:15433008
NCIt:C13013
BTO:0000772
EFO:0000572

Hope this helps.

Let me know if further information is needed.

Best regards,

Kalpana
----------------------------------------------
Kalpana Panneerselvam

IntAct-Senior Scientific Database Curator
European Molecular Biology Laboratory
European Bioinformatics Institute (EMBL-EBI)
Wellcome Genome Campus
Hinxton
Cambridge CB10 1SD
United Kingdom
Tel: +44 1223 494 468
email: ***@***.***

**Comment by lubianat** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Import GitHub issues assigned to me](https://trello.com/c/sLWt8New/4-import-github-issues-assigned-to-me)

**Comment by aleixpuigb** [comment]
Hi @lubianat, as it seems this issue has been resolved, can I close it and delete the branch in the associated PR?

**Comment by lubianat** [comment]
Sure!
Tiago




Il giorno mar 21 feb 2023 alle ore 08:52 Aleix Puig <
***@***.***> ha scritto:
