### ISSUE TITLE
Neuroglioform cell -> neurogliaform 

### ISSUE THREAD

**Issue by shawntanzk** [obophenotype/cell-ontology#1107]
CL:0000693 is currently labelled as neuroglioform cell, however, it seems that they are more known as neurogliaform cells (they are the same cells as evident by these papers [PMID: 3235828](https://pubmed.ncbi.nlm.nih.gov/3235828/) PMID: [3385194](https://pubmed.ncbi.nlm.nih.gov/3385194/))

Fix by changing label to neurogliaform cell and adding neuroglioform as a synonym? 

I am also unsure if they are a type of stellate interneuron (it is asserted that way at the moment)? @tgbugs could you help with this question? - If this is accurate, I will add neurogliaform morphology under stellate morphology in PATO and flatten this in CL after annotating and subsequently letting the reasoner organise it.

**Comment by patrick-lloyd-ray** [comment]
It seems that _neurogliaform_ is more common than _neuroglioform_, and a quick ngram confirms this, so I'm fine with the change. I wonder if the difference between 'glia' and 'glio' in this label is due to the Greek root of the term occurring with/without an 'o' in English translations ('gloia'/'glia'). I suppose it doesn't matter.
