### ISSUE TITLE
[NTR] enterocyte of colon

### ISSUE THREAD

**Issue by sfexova** [obophenotype/cell-ontology#1120]
Note - please check that the term does not already exist (check OLS: https://www.ebi.ac.uk/ols/ontologies/cl)

**Preferred term label:**
enterocyte of colon

**Synonyms**

**Definition (free text, please give PubMed ID in format PMID:XXXXXX)**
Enterocyte that is located in the colon.

**Parent cell type term (check the hierarchy here https://www.ebi.ac.uk/ols/ontologies/cl):**
enterocyte http://purl.obolibrary.org/obo/CL_0000584

**What is the anatomical structure that the cell is a part of? Please check Uberon: https://www.ebi.ac.uk/ols/ontologies/uberon**
colon http://purl.obolibrary.org/obo/UBERON_0001155

**Your nano-attribution (ORCID)**
0000-0003-3440-1876

**Any additional notes or concerns**

**Comment by paolaroncaglia** [comment]
@sfexova 
You requested 'enterocyte of colon'
Uberon has 'vacuolar absorptive cell of epithelium of colon', equivalent to
'enterocyte of epithelium of large intestine' and ('part of' some 'colonic epithelium')
(where 'colonic epithelium' is part of colon)
Is 'vacuolar absorptive cell of epithelium of colon' the same as what you meant by 'enterocyte of colon', please? If so, 
- [ ] I'll add 'enterocyte of colon' as [broad?] synonym of 'vacuolar absorptive cell of epithelium of colon'.

**Comment by sfexova** [comment]
I'll have to read a bit more about this - I have not seen enterocyte to be called _vacuolar_ absorptive cell in any of the papers I've seen though

**Comment by sfexova** [comment]
Hi @paolaroncaglia - I went through various enterocyte papers and also tried searching for 'vacuolar absorptive cell' papers and mentions and I have never seen it used as a synonym or in relation to enterocytes (and certainly not in humans), so I would rather not have this term linked/synonymous with vacuolar absorptive cell, I'm not convinced it would be correct

**Comment by paolaroncaglia** [comment]
Hi @sfexova ,
Thank you for looking into the 'vacuolar absorptive cell vs. enterocyte' issue above. Unfortunately, if I create 'enterocyte of colon' in the way you requested, it will result equivalent to 'vacuolar absorptive cell of epithelium of colon', and the automated ontology checks prevent this type of duplication by throwing an error. I'll attach a screenshot of Protege to show the equivalence. Basically, we need to clarify if the two terms are really the same or not. If they are the same, 'vacuolar absorptive cell of epithelium of colon' may be made a synonym of 'enterocyte of colon' if you prefer. If they are not the same, we need to establish where the difference lies. Thank you. Attaching screenshot in a moment...

**Comment by paolaroncaglia** [comment]
@sfexova 
FYI, the failed pull request is at https://github.com/obophenotype/cell-ontology/pull/1217/checks?check_run_id=3252622300

**Comment by paolaroncaglia** [comment]
And here's the full details of the equivalent term:
<img width="951" alt="Screen Shot 2021-08-05 at 15 26 26" src="https://user-images.githubusercontent.com/4982516/128357718-0f8af363-e856-4652-8f41-8e2328ca4619.png">

**Comment by sfexova** [comment]
I see - thanks @paolaroncaglia - I'll try to do more digging to see if the two cell types are or aren't the same but if they are it would be great if the main label could be changed to enterocyte of colon
I just wonder how the term label 'vacuolar absorptive cell' was arrived at in the first place - I mean they are children of enterocyte of epithelium of large intestine, just from defined as from a specific intestinal location, so isn't it weird they are not called enterocytes (of xy) too? There's no reference and I have never came across this term in a paper...

**Comment by paolaroncaglia** [comment]
@sfexova 
The reference is [FMA:263114](https://www.ebi.ac.uk/ols/ontologies/fma/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FFMA_263114), which doesn't have any publication attached. In FMA it's classified as
Subclass of:

    Vacuolar absorptive cell
    constitutional_part_of some Epithelium of colon

**Comment by sfexova** [comment]
yes, I meant there's no paper, so was wondering where FMA found the term...

**Comment by paolaroncaglia** [comment]
Hi @sfexova ,
Is there any update on this issue, please? Would it be possible to ask the external expert you referred to for other gut anatomogram terms, perhaps?
Alternatively, if we were to rename 'vacuolar absorptive cell of epithelium of colon' to 'enterocyte of colon' (and, for consistency, do the same for its sibling 'vacuolar absorptive cell of epithelium proper of large intestine'), I should check with the other CL editors too, as the terms were created before my time. We could make the case that 'vacuolar absorptive cell of epithelium of colon' has a child named 'enterocyte of appendix', and that the logical definition makes it clear that 'vacuolar absorptive cell of epithelium of colon' and 'enterocyte of colon' are the same, and that we could keep teh former as an exact synonym.
Please let me know so I can address your request. Thanks!
Paola

**Comment by sfexova** [comment]
Hi @paolaroncaglia,
I did quite an extensive search online but could not find any paper or publication that would use the term 'vacuolar absorptive cell', to me the terms seem a bit suspect and yes my preferred solution would be to rename them both to enterocytes and I also agree that structured as it is now in the ontology it follows that the 'vacuolar absorptive cells of xy' (being children of 'enterocyte of large intestine' and having, in the case of 'vacuolar absorptive cell of epithelium of colon', also 'enterocyte' labelled child term) must themselves be enterocytes too, so should be safe to rename. I personally think it would look better and be more consistent if all the terms in this branch were named enterocytes, so if you can try to do that - hopefully the other editors will agree - that would be fab!

**Comment by paolaroncaglia** [comment]
Hi @sfexova ,
Thanks for your feedback. I'll check with a few other CL editors, and will be happy to rename unless there are strong objections.
I'll post updates here.

**Comment by paolaroncaglia** [comment]
@dosumis @addiehl @nicolevasilevsky 
@sfexova and I would like to ask if any of you (or anyone else) has objections with renaming the following CL classes, please:
CL:1000347 vacuolar absorptive cell of epithelium of colon -> enterocyte of colon
CL:1000346 vacuolar absorptive cell of epithelium proper of large intestine -> enterocyte of epithelium proper of large intestine
while keeping the former labels as (exact?) synonyms.
Background/summary/rationale: Silvie requested a new term for 'enterocyte of colon' for the Single Cell Atlas anatomograms. If I created it, it would be logically equivalent to the existing 'CL:1000347 vacuolar absorptive cell of epithelium of colon' (see https://github.com/obophenotype/cell-ontology/issues/1120#issuecomment-893459451). Silvie suggests that 'enterocyte of colon' should be the primary label, based on her readings (see full thread). The two terms were created by Terry (no datestamp, but reasonable to say pre-2012), have FMA xrefs, but no published refs. In the 'enterocyte' CL branch, 14 terms are labelled 'enterocyte x' and only 2 'vacuolar absorptive cell x'. Based on Ontobee, 'vacuolar absorptive cell of epithelium of colon' is used by MP, uPheno and OBA, but the OBA example doesn't resolve; 'vacuolar absorptive cell of epithelium proper of large intestine' is not used in other ontologies.
I'd like to go ahead and rename unless there are objections please.
Thank you!
Paola

**Comment by nicolevasilevsky** [comment]
no objection from me

**Comment by paolaroncaglia** [comment]
Morning @dosumis and @addiehl ,
Next week I'll go ahead and rename 
CL:1000347 vacuolar absorptive cell of epithelium of colon -> enterocyte of colon
CL:1000346 vacuolar absorptive cell of epithelium proper of large intestine -> enterocyte of epithelium proper of large intestine
as per details in https://github.com/obophenotype/cell-ontology/issues/1120#issuecomment-915294029.
If you have any objections, please let me know by Monday 20th, otherwise I'll assume it's ok. This is needed to complete the set of CL terms for the SCA anatomograms. Thanks!
Paola

**Comment by dosumis** [comment]
> CL:1000347 vacuolar absorptive cell of epithelium of colon -> enterocyte of colon
> CL:1000346 vacuolar absorptive cell of epithelium proper of large intestine -> enterocyte of epithelium proper of large intestine

If you're happy these are the same thing, then sure (keeping the old term as synonym).  There are plenty of uses of the term absorptive cell for cells in the gut, and description of vacuoles in these cells, 

https://scholar.google.co.uk/scholar?hl=en&as_sdt=0%2C5&as_vis=1&q=vacuolar+absorptive+cell&btnG=

From the dates, this term seems be largely archaic now, but a regular google search finds occassional more recent examples

But: I think the key question is whether all enterocytes of the colon are vacuolated.  If only a subset are then I think we should have the term 'vacuolated enterocyte'. There is precedent for this: https://pubmed.ncbi.nlm.nih.gov/17901585/ (actually - this paper supports only a subset being vacuolated - in pigs at least - in a stage dep manner).

**Comment by paolaroncaglia** [comment]
Thanks @dosumis ,

> > CL:1000347 vacuolar absorptive cell of epithelium of colon -> enterocyte of colon
> > CL:1000346 vacuolar absorptive cell of epithelium proper of large intestine -> enterocyte of epithelium proper of large intestine
> 
> If you're happy these are the same thing, 

The logical def of the old term CL:1000347 supports that. There's not enough information associated with the old term to be 100% sure, but I think it's ok and I trust the submitter who's done more reading :-) 

> then sure (keeping the old term as synonym). 

Yes that was the plan. I'll make them narrow synonyms.

> There are plenty of uses of the term absorptive cell for cells in the gut, and description of vacuoles in these cells,
> 
> https://scholar.google.co.uk/scholar?hl=en&as_sdt=0%2C5&as_vis=1&q=vacuolar+absorptive+cell&btnG=
> 
> From the dates, this term seems be largely archaic now, but a regular google search finds occasional more recent examples
> 
> But: I think the key question is whether all enterocytes of the colon are vacuolated. If only a subset are then I think we should have the term 'vacuolated enterocyte'. There is precedent for this: https://pubmed.ncbi.nlm.nih.gov/17901585/ (actually - this paper supports only a subset being vacuolated - in pigs at least - in a stage dep manner).

Good then, I'll add CL:NEW 'vacuolated enterocyte' with dbxrefs PMID:17901585 + your ORCID.

Thanks for your feedback!

**Comment by paolaroncaglia** [comment]
@sfexova 
CL_1000347 (was: 'vacuolar absorptive cell of epithelium of colon') is now labelled 'enterocyte of colon' as requested.
The change will be visible in the next CL release. (Not scheduled yet, but the last release was 26 days ago, so probably not too long now.)

@dosumis 
I've added CL_0009067 (vacuolated fetal-type enterocyte) as agreed.

**Comment by paolaroncaglia** [comment]
P.S. @sfexova @ngeorgeebi cc @dosumis 
All CL and Uberon terms requested by SCA for anatomograms have now been added (pending CL release of the most recent change above).

**Comment by sfexova** [comment]
Hi @paolaroncaglia thanks! However, I see in the screenshot above that 'enterocyte of appendix' is a child of 'enterocyte of colon' (as well of just 'enterocyte'), which it shouldn't be (and it would break the anatomograms) - can you please remove it from there?

**Comment by paolaroncaglia** [comment]
Hi @sfexova ,
Hm, I thought that had been fixed. I'll look into it (whether the issue is in CL or Uberon), but I'm on leave today and tomorrow, so I re-opened the ticket and prioritized it, and I'll get back to you. Thanks.

**Comment by dosumis** [comment]
Looks like gut partonomy still needs fixing in Uberon:

![image](https://user-images.githubusercontent.com/112839/139824560-765a9852-d1b7-4213-a845-7e6b7508ef35.png)

The classification is inferred from this.

**Comment by paolaroncaglia** [comment]
Thanks @dosumis , that's why I was perplexed, I did address the partonomy in Uberon (https://github.com/obophenotype/uberon/issues/1869#issuecomment-855978938 and related https://github.com/obophenotype/uberon/issues/1920#issuecomment-859419145). I think I remember that the anatomy changes percolated even to Mondo and EFO, but I'll need to double-check everything again. Hm.

**Comment by dosumis** [comment]
Just looked again.  I think this is just a timing issue.  It is fixed in Uberon (the relationship of vermiform appendix to caecum in the edit file is connected_to).  I think this will just be fixed by making sure  imports are updated for CL and Uberon and then running new releases.  There might be a horrible circular issue with order of releases and stale imports that's making this harder to achieve than it should be.  (@matentzn - another case that would be fixed by base file).

**Comment by paolaroncaglia** [comment]
Hi @dosumis (cc @sfexova )

> I think this is just a timing issue. It is fixed in Uberon (the relationship of vermiform appendix to caecum in the edit file is connected_to). I think this will just be fixed by making sure imports are updated for CL and Uberon and then running new releases. There might be a horrible circular issue with order of releases and stale imports that's making this harder to achieve than it should be. (@matentzn - another case that would be fixed by base file).

So should we ask for updates on this ticket (it's a priority in the technical board)? Or should I just open a ticket asking to 1) update imports for CL and Uberon and then 2) run new releases? I've seen several bits of conversation on imports fly past in GitHub notifications while I was on leave... Thanks

**Comment by paolaroncaglia** [comment]
Hi @sfexova ,
FYI, I just followed up on the technical issue that seems to prevent resolution of this ticket.

**Comment by paolaroncaglia** [comment]
Update: the underlying issue is quite complex; Uberon developers are well aware of it and are discussing it actively; they're optimistic that it can be done, but resources need to be allocated for a fair chunk of time (and that's well beyond my control). 
I don't think that a quicker workaround exists based on what the developers write, so all we can do is stay tuned...

**Comment by dosumis** [comment]
Context: We have a known problem with circular imports => Zombie relationships.  We are working on fixing this individual case for this release (if not this week, we can run another release v.soon). Fixing the bigger problem will take resources and a chunk of time. I'm hoping we can do this in December.

**Comment by paolaroncaglia** [comment]
Hi @sfexova and @dosumis , 
Following up on this, there was a CL release 2 days ago, and unfortunately 'enterocyte of appendix' is still a child of 'enterocyte of colon' (as well of just 'enterocyte'), due to the Uberon import. David was hoping to address the wider issue next month, but I don't know if plans for resource allocation have been finalized, see https://github.com/obophenotype/uberon/issues/2094#issuecomment-966506578. Silvie, what are the timelines and requirements for the SCA anatomograms? You mentioned that the current term placement would break them - do we need to meet to address this, or can it wait? Is there any solution you could adopt in the meantime (e.g. exclude enterocyte terms)?
Please let us know here or on Slack/email, I'd like to make sure that we don't "drop" anything. Thanks.

**Comment by dosumis** [comment]
@shawntanzk @matentzn  - seems we still didn't slay the zombie manually.  Is there any way we might be able to get a release where this is not broken, or do we need to wait for the new import mechanism to be working.

**Comment by shawntanzk** [comment]
@matentzn - can we remove all the axioms on that (including the import file ones) and use IMP=false for the next release as a temp fix?  I need a CL release soon anyway, so happy to do this (though ideally after uberon release - think there's a term change due to obsoletion in uberon that needs to go first... lol more circular funtimes). So basically:
1) uberon release
2) refresh uberon import in CL
3) remove axioms in uberon import file
4) CL release with IMP=false
Not sure if it will work?

**Comment by matentzn** [comment]
Lets discuss in meeting later today, just mention it to me. Its easy to fix

**Comment by paolaroncaglia** [comment]
Thanks everyone :-)

**Comment by shawntanzk** [comment]
So this will be fixed once this release gets approved: https://github.com/obophenotype/cell-ontology/pull/1330 
However caveat being that its not a permanent fix - if anyone refreshes uberon import, it will probably come back again :( part of the cyclical problem basically. But I guess for now at least this can be used.

**Comment by shawntanzk** [comment]
Fixed in latest release: https://github.com/obophenotype/cell-ontology/releases/tag/v2021-11-25
![Screenshot 2021-11-26 at 10 14 41](https://user-images.githubusercontent.com/76212760/143564684-b8812519-aa1e-4f1c-9cf9-a223ac62f6b2.png)

**Comment by paolaroncaglia** [comment]
Reopening because we need to inform and discuss with the submitter :-)

**Comment by shawntanzk** [comment]
sorry - habit of doing this with the boards I handle to keep them clean >.<

**Comment by paolaroncaglia** [comment]
@sfexova 
In brief: the latest release of the Cell Ontology (CL) contains the fix you need for 'enterocyte of appendix'.
This is the 2021-11-25 Release (v2021-11-25) here: https://github.com/obophenotype/cell-ontology/releases/tag/v2021-11-25
Your team should download it asap and use it for the anatomograms.
The fix is very temporary: as soon as CL needs a new Uberon term to be imported, the issue will come back, until the technical OBO team has time to work on a longer-term fix. Do the anatomograms link to CL and Uberon dynamycally, or are they based on "fixed" version i.e. not updated in time?
@dosumis I hope this is a correct interpretation.
@sfexova please contact us if you need to discuss this.

**Comment by matentzn** [comment]
We have already implemented a pipeline that will avoid the issue from coming back - no need to worry about that.

**Comment by paolaroncaglia** [comment]
> We have already implemented a pipeline that will avoid the issue from coming back - no need to worry about that.

Thanks @matentzn et al, that's great!

**Comment by paolaroncaglia** [comment]
@sfexova 
That should be all of the CL terms you requested for SCA then. I'll close this ticket.
