### ISSUE TITLE
[Synonym] L5 ET Synonyms 

### ISSUE THREAD

**Issue by raymond-sanchez** [obophenotype/cell-ontology#1147]
**CL term**
L5 ET

**Synonym to be added**
**L5b neurons**
Reference DOI: 10.1016/j.neuron.2011.07.029
broad
______

**Thick-tufted layer 5 pyramidal neurons**
Reference DOI: 10.3389/fncel.2015.00233
broad
_____

**Burst-firing layer 5 neurons**
Reference DOI: https://doi.org/10.3389/fncel.2011.00001
broad
______

**Pyramidal tract (PT) neurons**
Reference DOI: 10.1038/nrn3469
narrow/exact
______

**Subcerebral projection neurons (SCPN)**
Reference DOI: https://doi.org/10.1016/j.neuron.2005.08.030
broad
______

**Pyramidal tract-like (PT- l)**
Reference DOI: https://doi.org/10.1016/j.cell.2019.09.023
related

_____

**Thick-tufted layer 5 neuron (TTL5)**
Reference DOI: 10.3389/fncel.2015.00233
broad

**Comment by raymond-sanchez** [comment]
@shawntanzk

**Comment by shawntanzk** [comment]
@raymond-sanchez - wonder how you seperate between broad, exact, and related?

@dosumis - I've currently put everything as has_exact_synonym - was wondering if changing to others would have any implications in the ontology/search? 

Notes: 
Thick-tufted layer 5 neuron (TTL5) and Thick-tufted layer 5 pyramidal neurons are very similar synonyms and have the same reference, and since all L5 ET are pyramidal - ill merge them into one synonym

"pyramidal tract-like is used because, unlike pyramidal tract neurons in the motor cortex, neurons in the structures like the auditory cortex do not project to the spinal cord." - @dosumis will leaving a comment on synonym entry be the right way to handle this? (note that L5 ET is a pan cortical entry)

**Comment by raymond-sanchez** [comment]
@shawntanzk I wasn't sure of the criteria you all had used already for this, so "broad" here refers to terms that could apply to other things (L5b neurons in another region of cortex, for example), "exact" for things that could only apply to L5 ET, and the one "related" because the neurons referenced were similar to MOp L5 ET neurons except they did not project to spinal cord. 

If L5 ET is a pan-cortical entry however, that renders my distinctions moot and I'd leave it up to your discretion
