### ISSUE TITLE
NTR: 3 new terms

### ISSUE THREAD

**Issue by GoogleCodeExporter** [obophenotype/cell-ontology#121]
```
Label: CD3-positive T Cell
Genus/parent: CD3 subunit with immunoglobulin domain

Label: CD19-positive B cell
Genus/parent: CD19 molecule

Label: CD19-positive,CD10-positive B cell
Genus/parent: ?

Thank you!
```

Original issue reported on code.google.com by `david.fo...@gmail.com` on 2 May 2014 at 3:11

**Comment by addiehl** [comment]
'B cell, CD19-positive' CL:0001201 now exists.  'CD3-positive T Cell' is not needed, since all T cells have CD3 as part of the T cell receptor complex (work needs to be done to ensure this is inferred through reasoning).

'precursor B cell' is logically defined as having 'CD19 molecule' and 'neprilysin' AKA CD10, so no changes needed.
