### ISSUE TITLE
HubMap CCF reporter: same cell type name, different IDs?

### ISSUE THREAD

**Issue by paolaroncaglia** [obophenotype/cell-ontology#1260]
Spotted during Alex' talk at CELLS 2021 so didn't have much time to examine the underlying data/reason:
3 occurrences of "adipocyte", with 3 different CL IDs?
Mousing over the entities results in a "could not fetch data" note.

![Screen Shot 2021-09-15 at 16 51 26](https://user-images.githubusercontent.com/4982516/133456663-2a45d327-002f-4ad5-bd60-e202542d36a3.png)

@emquardokus please feel free to close this if there's a simple explanation :-)  
(or if the issue should be ticketed with HubMap instead, I just wanted to bring this up quickly.)

**Comment by emquardokus** [comment]
@paolaroncaglia Thank you for mentioning this and asking. 
This unfortunately was a screenshot from the "All organs" view from our ASCT+B reporter visualization, so it represents all cells and annotations from all 11 organs from 1st release.  One note on 3 instances of "adipocyte" with 3 different IDs---the label shown is what the author of table provided and the blue boxes around them on the vis shown here indicate a "mismatch" between name given by author and ontology label. 
So these are actually 3 unique adipocytes located in different locations within an organ or between organ tables. If you go back to look at what organs those are associated with, you'll see heart has adipocyte in one part of it assigned to "fat cell CL:0000136" which is located in the Myocardium of right ventricle of the heart.  Another instance of "adipocyte" is assigned to "epicardial adipocyte CL:1000309" of the epicardium of the heart and the 3rd instance of "adipocyte" is assigned to subcutaneous fat cell | CL:0002521 in the "Skin" organ table. Please check out the ASCT+B reporter to play with these features.  It would be interesting to hear whether you or others think the ontology label should be used (which is always longer) or the common cell type name that author provides with reference to more specific ontology ID/label.
I will look into why the information boxes are not fetching when CL id's are present because they absolutely should be.  There might be some IRI address fetching issue
