### ISSUE TITLE
Make 'auditory system neuron' broader.

### ISSUE THREAD

**Issue by dosumis** [obophenotype/cell-ontology#1264]
**CL term**

auditory hair cell
http://purl.obolibrary.org/obo/CL_0000202
A mechanoreceptor cell located in the inner ear that is sensitive to auditory stimuli. The accessory sensory structures are arranged so that appropriate stimuli cause movement of the hair-like projections (stereocilia and kinocilia) which relay the information centrally in the nervous system. [ MESH:A08.663.650.250 ]

![image](https://user-images.githubusercontent.com/112839/134077250-db22e2c1-0225-4dbe-a041-c06a9f5398fb.png)

**Description of problem**

1. CL terms like links to Uberon
2. This definition is, like many in CL,  has a very strong mammalian/human bias.  Auditory hair cells exist in other contexts in vertebrates
https://www.ncbi.nlm.nih.gov/pmc/articles/PMC3023005/

**Suggested solution**

Broaden the meaning of 'auditory hair cell' to cover all hair cells with an auditory function.  Question - should we keep the link to ear - assuming this is meant in a broad sense?   Make a new, more specific class for 'cochlea auditory hair cell' with part_of relationship to 'spiral organ of cochlea':

Equivalent to:
'auditory hair cell' and part_of some 'spiral organ of cochlea'

**Comment by shawntanzk** [comment]
Changes:
1) Change def to: "a mechanoreceptor cell that is sensitive to auditory stimuli." I think the gloss can remain the same, seems to be the same in fish/frogs 
2) Change asserted class to sensory hair cell since in fish, these cells are in lateral line organ. 
3) Remove 'part of' some 'spiral organ of cochlea' axiom, and create a class "cochlea auditor hair cell" with the following:
Definition: "An auditory hair cell found in the cochlea" 
Equiv class: 'auditory hair cell' and part_of some 'spiral organ of cochlea'
4) Move synonyms: cochlear hair cell, inner ear hair cell, & inner ear receptor cell to "cochlea auditor hair cell" (@dosumis not sure about implications of this where people have used this term before? Is leaving a comment that cochlea auditory cells should use the more specific term instead sufficient? The good thing I guess is that given that it is broader, the uses wont be wrong per se)
