### ISSUE TITLE
[Typo/Bug] mononuclear & multinucleate phagocyte have no children!

### ISSUE THREAD

**Issue by dosumis** [obophenotype/cell-ontology#1266]
**CL term**

mononuclear phagocyte  http://purl.obolibrary.org/obo/CL_0000113 

**Description of typo, bug or error**

![image](https://user-images.githubusercontent.com/112839/134666618-863ff1ba-90c6-444f-834f-5b890104f8cf.png)

@addiehl - any suggestions for how we might efficiently populate these classes?

**Comment by paolaroncaglia** [comment]
Also see https://github.com/obophenotype/cell-ontology/issues/561.

**Comment by jychien** [comment]
Additional references pertaining to this issue, which states monocyte, macrophages, and dendritic cells as children on mononuclear phagocytes (MNP):

- https://www.sciencedirect.com/science/article/pii/S1074761321002934
- https://www.frontiersin.org/articles/10.3389/fimmu.2017.00499/full

You can also see in the [macrophage](https://www.ebi.ac.uk/ols/ontologies/cl/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FCL_0000235) definition that it is a mononuclear phagocyte. 
![Screenshot 2023-09-21 at 10 56 05 AM](https://github.com/obophenotype/cell-ontology/assets/52470876/905e9f63-eb7c-4355-aa60-10b150d94b3d)

Also, is there a reason why mononuclear phagocyte is not a child of [mononuclear cell](https://www.ebi.ac.uk/ols/ontologies/cl/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FCL_0000842&lang=en&viewMode=PreferredRoots&siblings=false)?

I think the general confusion is that under leukocyte, there is a division between mononuclear cell and myeloid cell. However, typically, the distinction is made between lymphocyte vs myeloid cells because the cell lineage is derived from [common lymphoid progenitor](https://www.ebi.ac.uk/ols/ontologies/cl/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FCL_0000051) and [common myeloid progenitor](https://www.ebi.ac.uk/ols/ontologies/cl/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FCL_0000049). There are many diagrams online, but here is one from [wikipedia](https://en.wikipedia.org/wiki/Myeloid_tissue). 

![Screenshot 2023-09-21 at 11 11 37 AM](https://github.com/obophenotype/cell-ontology/assets/52470876/3bda191e-b8a3-4645-b9f6-295e57e2d4b0)

**Comment by dosumis** [comment]
- [ ] TODO - mononuclear phagocyte should be under 'mononuclear cell'
- [ ] TODO  - populate subclasses under 'mononuclear phagocyte' 
     These are currently under the general term 'phagocyte'

**Comment by aleixpuigb** [comment]
> TODO - populate subclasses under 'mononuclear phagocyte'

macrophage
monocyte
dendritic cell
osteoclast
