### ISSUE TITLE
Create a DP for has-soma-location pattern

### ISSUE THREAD

**Issue by cmungall** [obophenotype/cell-ontology#1389]
So far we have a DP documented for cells part of anatomy:

https://obophenotype.github.io/cell-ontology/patterns/cellPartOfAnatomicalEntity/

But none for has-soma-location(HSL)

We need to add these, and make the ontology consistent (which @shawntanzk has been doing -see #1337) 

We need to document whether

 1. We *only* use HSL for neurons->uberon
 2. We use a mixture of part-of and HSL as appropriate
     - typically use HSL for equivalence axioms (principle: weaker properties in EC -> stronger inferences)
     - add supplemental part-of hidden GCIs if we know the neuron is not projecting outside the anatomical area

While 1 is both safer and easier to implement, I worry we will lose crucial inferences in CL

In particular I worry about loss in:

 - gene expression queries that propagate over part-of
 - entailments in ontologies that use CL for logical definitions

To restore these inferences we will need to add a lot of hidden GCIs

## Alternative proposal: radical mereological inclusivity

We abandon HSL, we go back to using simple powerful part-of relations.

We conceive of uberon brain regions such as hippocampus as having 'classic boundaries' at one level of granularity, but when zoomed in to the subcellular level the hippocampus itself has synaptic parts that interleave with other brain regions. These could be described using simple projects-into relationships.

This would require some minor changes in uberon: the existing adjacency relations (not that useful IMO) would need to be changed to something like 'grossly adjacent to'.

Gene expression queries would be more inclusive but arguably more correct since expression is in the soma.

**Comment by shawntanzk** [comment]
tagging @dosumis here

**Comment by shawntanzk** [comment]
are there any further thoughts on this?

My big worry with ditching HSL for part_of is that there will probably be quite a bit of unsats generated by it, and im not sure how to handle those unsats.

**Comment by dosumis** [comment]
Happy to make a pattern, but one with an EquivalentClass axiom would only be useful for the rare neuron classes we want to define by location.  For everything else we have:

https://obophenotype.github.io/cell-ontology/relations_guide/#recording-location

The vast majority of neuron types need to be defined with some heterogenous mix of relations - as applicable to specific use-cases. Training-wise, a well written piece of text just works better than trying to document with patterns.  I think worthwhile despite the danger of duplication and stale docs.  We are working on a similar doc for Uberon. 

> ### Alternative proposal: radical mereological inclusivity
> We abandon HSL, we go back to using simple powerful part-of relations.

This would create a mess as we have a bunch of other subproperties of overlaps that are used for the location of other parts of neurons (synapses, projections).  Also, we already have **massive** usage of these relations in DAO & VFB.  

> gene expression queries that propagate over part-of
> entailments in ontologies that use CL for logical definitions

I would like to document examples of these so that we can think about how to work with them.  VFB deals with expression on the query side.  I guess the other cases you are thinking about are Mondo & phenotype/trait ontologies.  I wonder whether property chains might be sufficient to deal with these.

**Comment by dosumis** [comment]
Closing as I think documentation of any inferences missing due to has_soma_location use + proposed remedies should go on a new ticket.
