### ISSUE TITLE
[Typo/Bug] Duplicated exact synonym in CL:0002430 and CL:0002431

### ISSUE THREAD

**Issue by paola-scibite** [obophenotype/cell-ontology#1390]
**CL term**
CL:0002430 CD4-intermediate, CD8-positive double-positive thymocyte
CL:0002431 CD4-positive, CD8-intermediate double-positive thymocyte

**Description of typo, bug or error**
Both terms have the same exact synonym except for an uppercase/lowercase letter. Not sure if CL has checks for duplicated exact synonyms - if it does, that may be why this case wasn't picked up. The synonym is T.4int8+.Th / T.4int8+.th. It should be removed from CL:0002431 please.

**Comment by paolaroncaglia** [comment]
@matentzn please (no rush): does CL have automated checks in place to detect if an exact synonym is duplicated on more than one term? I expect it has, just checking. Thanks.

**Comment by addiehl** [comment]
These synonyms came from the [ImmGen](https://www.immgen.org) project. Unfortunately, ImmGen does not provide a straightforward way to search their cell types. They do show "T_4int8+_Th" and "T_4+8int_Th" on this [page](http://rstats.immgen.org/MyGeneSet_New/index.html), under "ab T Cells" in the "Microarray V1" tab. I suspect CL:0002430 corresponds to "T_4int8+_Th", and CL:0002431 corresponds to "T_4+8int_Th".  In the ImmGen iPhone app these cell types are shown as "T.4int8+.Th" and "T.4+8int.Th" for what appears to be the same dataset. Note that ImmGen used to use a Flash-based interface years ago that may have shown these synonyms with a period rather than an underbar.

So I suspect this was a typo on Terry's part when he entered the synonym for CL:0002431. Probably we should list both synonyms (with the _ or . characters) for each of these cell types.

As a longer term project it might be worth asking ImmGen for a proper data dictionary of their cell types.

**Comment by matentzn** [comment]
@paolaroncaglia Make sure we have such QC issues separately from from the concrete synonym clashes, and add them to our board: https://github.com/orgs/obophenotype/projects/5 

This makes sure that they will be dealt with soon :)

**Comment by bvarner-ebi** [comment]
Created https://github.com/obophenotype/cell-ontology/pull/1394
