### ISSUE TITLE
[NTR]Choroidal melanocyte

### ISSUE THREAD

**Issue by paulacalipho** [obophenotype/cell-ontology#1409]
**Preferred term label:** Choroidal melanocyte

**Synonyms**: -

**Definition**
Choroidal melanocytes are melanin-producing cells in the uvea of the human eye. Their cellular functions and extracellular interactions are distinct to skin melanocytes. They are involved in photoprotection, regulation of oxidative damage and immune responses. Choroidal melanocytes might have both neuroectodermal as well as mesectodermal origins. [PMID: 31819095, PMID: 34082079]

**Parent cell type term:**
Melanocyte (CL:0000148)

**What is the anatomical structure that the cell is a part of?**
Optic choroid (UBERON:0001776)

**Your nano-attribution (ORCID)**
0000-0002-0819-0473

**Any additional notes or concerns** We are mapping cell types in Cellosaurus to CL. We found most of the terms, only few are missing. We  would be grateful if you could create them. This is one of them. Many thanks!

**Comment by bvarner-ebi** [comment]
@paulacalipho, thank you for the information on this new term.

I am planning to enter the definition for choroidal melanocyte as:
**A melanocyte located in the vascular uvea and involved in photoprotection, regulation of oxidative damage and immune responses.** 
(PMID:31819095)

I removed the reference to "human" since I found papers referring to these cells in mice, dogs and cats as well. If human choroidal melanocytes have unique features compared to other taxa, we could consider restricting this term to homo sapiens.

I placed the additional information from your original definition in a comment on the term.

Regarding the anatomical structure you provided (optic choroid (UBERON:0001776)), there would be some discrepancy in anatomical location between the text definition (uvea) and the logical axiom (optic choroid). To align these, would using uvea (UBERON:0001768) as the anatomical structure be acceptable? That way it would cover the other structures noted in your reference (PMID:31819095): "Choroidal melanocytes (HCMs) are melanin-producing cells in the vascular uvea of the human eye **(iris, ciliary body and choroid**)" compared to just the choroid.

I look forward to your feedback on the proposed definition and anatomical structure.

**Comment by paulacalipho** [comment]
@bvarner-ebii, I agree with your definition and proposal of anatomical location to uvea (UBERON:0001768) as the anatomical structure. 
If you think the comment has no added value, you can delete it. 
Thank you very much for your input and for integrating this term in CL.

**Comment by bvarner-ebi** [comment]
Thank you for the quick reply, @paulacalipho.
I updated the definition and anatomical structure accordingly. I think the comments are useful for context in case we refine the term or related terms in the future.
