### ISSUE TITLE
[NTR] Podocyte-like epithelial cell

### ISSUE THREAD

**Issue by paulacalipho** [obophenotype/cell-ontology#1415]
**Preferred term label:** Podocyte-like epithelial cell

**Synonyms**: -

**Definition**: Podocyte-like epithelial cells have mRNA expression for the podocyte markers synaptopodin, nestin, and CD2AP and are found in the urine of patients with focal segmental glomerulosclerosis and healthy individuals [PMID: 19955187]

**Parent cell type term:** epithelial cell of glomerular capsule (CL:1000450)

**What is the anatomical structure that the cell is a part of?**: glomerular capsule (UBERON:0001230)

**Your nano-attribution (ORCID)**: 0000-0002-0819-0473

**Any additional notes or concerns**: -

**Comment by dosumis** [comment]
As this is found in the urine of healthy individuals, I think it is in scope, but I would like further discussion.   Based on the reference, maybe this should be 'shed podocyte'; 'develops from' (?) podocyte (glomerular visceral epithelial cell);  'part of' or 'located in' urine.

**Comment by paulacalipho** [comment]
@dosumis : thank you for your pertinent suggestions. Does "originates from" exist?

**Comment by bvarner-ebi** [comment]
Based on a cursory review of the paper [PMID: 19955187], it seems like this new term request is referring to a shed podocyte that has been potentially altered by experimentation:

_"These results indicate that SV40 T antigen transformation and single-cell cloning did indeed affect podocyte marker expression..."_

_"The effects of this SV40 T antigen on podocyte marker expression were inconsistent among human subjects. SV40 transformation is known to alter cell gene expression, and the regulation is cell specific..."_

_"Serial passage may also contribute to the loss of podocyte markers."_

_"These results suggest that transformed urinary cells in bulk culture, while heterogeneous with regard to podocalyxin expression, cannot be clearly separated into podocyte-like and non-podocyte-like cells."_

_"Although the alteration of gene expression by transformation remains a problem, we believe that this problem may be overcome with further work and that urinary podocyte cell lines will prove to be increasingly useful tools..."_

If these "podocyte-like epithelial cells" have features that distinguish them from native podocytes due to effects of culturing/cloning, would it be appropriate to add to CL?
Or does it warrant a new term just for the fact that the cell can be found in a new location (glomerulus vs urine)?

**Comment by paulacalipho** [comment]
@bvarner-ebi: thanks for your input. I understand that the term is not appropriate for CL. We retract the term request. How to proceed for this?

**Comment by paolaroncaglia** [comment]
@paulacalipho @bvarner-ebi to do that, Bradley should close the ticket and add the label "invalid". Thank you.

**Comment by bvarner-ebi** [comment]
Thank you for the updates, @paulacalipho and @paolaroncaglia.
