### ISSUE TITLE
[NTR] Oligodendrocyte/type-2 astrocyte progenitor cell

### ISSUE THREAD

**Issue by paulacalipho** [obophenotype/cell-ontology#1438]
**Preferred term label:** Oligodendrocyte/type-2 astrocyte progenitor cell

**Synonyms**
 O-2A/OPCs
oligodendrocyte type 2 astrocyte (O-2A) progenitor cells
oligodendrocyte-type-2 astrocyte progenitor cells

**Definition**: Oligodendrocyte/type-2 astrocyte progenitor cells can generate oligodendrocytes and type-2 astrocytes [PMID: 24133281, PMID: 2182078, PMID: 11756508, PMID: 9826671]

**Parent cell type term:** neuron associated cell (sensu Vertebrata) (CL:0000123)

**What is the anatomical structure that the cell is a part of?** brain (UBERON:0000955)

**Your nano-attribution (ORCID)**: 0000-0002-0819-0473

**Any additional notes or concerns**
1) These cells can be purified from optic nerves and other regions of the embryonic, postnatal, and adult rat CNS and can be differentiated _in vitro_ to oligodendrocytes and type-2 astrocytes. I do not know if this must be indicated somewhere
2) the synoynm "oligodendrocyte precursor cells" is sometimes used in papers to refer to "oligodendrocyte/type-2 astrocyte progenitor cells". This "synonym" should not be included here because "oligodendrocyte precursor cell" CL:0002453 corresponds to a different cell type.

**Comment by bvarner-ebi** [comment]
Hi, @paulacalipho,

Thank you for the request.

Would the following definition be acceptable?
A progenitor cell of the central nervous system that can generate oligodendrocytes and type-2 astrocytes.

I also found this synonym:
O2A/OPC (PMID:11756508)

> These cells can be purified from optic nerves and other regions of the embryonic, postnatal, and adult rat CNS and can be differentiated in vitro to oligodendrocytes and type-2 astrocytes. I do not know if this must be indicated somewhere.

^ I could add this as a comment. Is this statement supported by PMID: 2182078? I am only able to access the abstract for that paper.

>the synoynm "oligodendrocyte precursor cells" is sometimes used in papers to refer to "oligodendrocyte/type-2 astrocyte progenitor cells". This "synonym" should not be included here because "oligodendrocyte precursor cell" CL:0002453 corresponds to a different cell type.

^ I could also add this as a comment. Do you have an example reference that illustrates this?

**Comment by paulacalipho** [comment]
Hi   @bvarner-ebi, thanks for taking care of this request.

I agree with the definition and additional synonym you suggest

OK to add the comments:

a- "These cells can be purified from optic nerves and other regions of the embryonic, postnatal, and adult rat CNS and can be differentiated in vitro to oligodendrocytes and type-2 astrocytes". 
This statement is supported by PMID: 2182078 (if you do not have access I can try to send you the pdf (how??) https://reader.elsevier.com/reader/sd/pii/0896627390901102?token=6F4B0F94D2E675D469E2E621395CD91C7C1207C0AC402A134E683AA214D353CFB5EA346EAF788C48EBC27D3405C010E8&originRegion=eu-west-1&originCreation=20220203074610)

b- the synoynm "oligodendrocyte precursor cells" is sometimes used in papers to refer to "oligodendrocyte/type-2 astrocyte progenitor cells". This term should not be included here as synonym because "oligodendrocyte precursor cell" CL:0002453 corresponds to a different cell type. 
Example from PMID: 11756508: "... it is well established that oligodendrocytes can be generated from oligodendrocyte-type-2 astrocyte progenitor cells ([Raff et al., 1983](https://www.ncbi.nlm.nih.gov/pmc/articles/PMC6757619/#B34); [Skoff and Knapp, 1991](https://www.ncbi.nlm.nih.gov/pmc/articles/PMC6757619/#B43)), which also are referred to as oligodendrocyte precursor cells ([Raff et al., 1983](https://www.ncbi.nlm.nih.gov/pmc/articles/PMC6757619/#B34); [Skoff and Knapp, 1991](https://www.ncbi.nlm.nih.gov/pmc/articles/PMC6757619/#B43)) and abbreviated here as O2A/OPCs."

**Comment by bvarner-ebi** [comment]
Hi @paulacalipho,

2 follow-up questions, please:

1- Is there evidence that the 'oligodendrocyte/type-2 astrocyte progenitor cell' is indeed a different cell type from 'oligodendrocyte precursor cell'?

2- Do you know if this cell type 'is a' or 'develops from a' glioblast?

**Comment by bvarner-ebi** [comment]
Hi @paulacalipho,

Some additional findings that seem to suggest these cell types ('oligodendrocyte/type-2 astrocyte progenitor cell' and 'oligodendrocyte precursor cell') may be referring to the same thing. 
From PMID:10704434:

"Oligodendrocytes arise from a well-defined precursor cell that also can give rise to a specific astrocyte population (the type-2 astrocyte) in vitro ([Raff et al. 1983](https://www.ncbi.nlm.nih.gov/pmc/articles/PMC2174536/#Raffetal1983)), although, thus far, it appears that this astrocyte pathway is not used during development ([Skoff 1990](https://www.ncbi.nlm.nih.gov/pmc/articles/PMC2174536/#Skoff1990)). Due to this disparity, this single precursor cell is alternatively called an oligodendrocyte type-2 astrocyte (O-2A) progenitor or an oligodendrocyte precursor cell (OPC)."

From https://doi.org/10.1038/s41598-017-14207-0:

"In addition, we found that Venus-positive OPCs were able to differentiate to type II astrocytes. In vivo, OPCs and oligodendrocytes express Venus, and some of astrocytes were positive for Venus in the ventral cortex."

From https://doi.org/10.1242/dev.126409:

"Oligodendrocytes are the myelinating cells of the central nervous system (CNS), and the last major neural phenotype to form during development. They arise from oligodendrocyte progenitor cells (OPCs), which can generate either oligodendrocytes or astrocytes depending on context ([ffrench-Constant and Raff, 1986]); [Raff et al., 1983a]."

I look forward to receiving your feedback!

**Comment by paulacalipho** [comment]
Hi @bvarner-ebi Thanks for reviewing this term. I agree with you that 'oligodendrocyte/type-2 astrocyte progenitor cell' and 'oligodendrocyte precursor cell' seem to refer to the same entity.

Do you think that the following terms should be added to oligodendrocyte precursor cell" (CL:0002453) as synonyms?
Oligodendrocyte/type-2 astrocyte progenitor cell
O2A/OPC
O-2A/OPCs
oligodendrocyte type 2 astrocyte (O-2A) progenitor cells
oligodendrocyte-type-2 astrocyte progenitor cells

**Comment by bvarner-ebi** [comment]
Thank you for all the feedback, @paulacalipho!

Based on your feedback and literature reviews, we added comments and broad synonyms to CL:0002453 'oligodendrocyte precursor cell'.

These updates reflect the idea that 'oligodendrocyte/type-2 astrocyte progenitor cell' and related terms may be referring to the same entity or possibly to a precursor to oligodendrocyte- and type-2 astrocyte precursor cells. I plan to submit a NTR for the latter since it does not yet exist in CL.

Full discussion can be viewed in PR #1442.

**Comment by paulacalipho** [comment]
@bvarner-ebi  Many thanks to you!
