### ISSUE TITLE
[NTR] Thymic nurse cell

### ISSUE THREAD

**Issue by paulacalipho** [obophenotype/cell-ontology#1439]
**Preferred term label:** Thymic nurse cell

**Synonyms**: -

**Definition**: "Thymic nurse cells are large epithelial cells found in the cortex of the thymus and also in cortico-medullary junction. They internalize thymocytes through extensions of plasma membrane. The cell surfaces of thymic nurse cells and their cytoplasmic vacuoles express MHC Class I and MHC Class II antigens. The interaction of these antigens with the developing thymocytes determines whether the thymocytes undergo positive or negative selection." [https://en.wikipedia.org/wiki/Thymic_nurse_cell]

**Parent cell type term:** epithelial cell of thymus (CL:0002293)

**What is the anatomical structure that the cell is a part of?**: 
cortex of thymus (UBERON:0002123)
thymus corticomedullary boundary (UBERON:0003988)

**Your nano-attribution (ORCID)**: 0000-0002-0819-0473

**Any additional notes or concerns**: According to Wikipedia: "The thymic nurse cells in the cortico-medullary junction express cytokeratin 5 (K5) and cytokeratin 8 (K8), whereas the ones in the cortex express only cytokeratin 8." Seems this is a mix of two populations. Should terms be created for these two populations? Many thanks

**Comment by bvarner-ebi** [comment]
> **Any additional notes or concerns**: According to Wikipedia: "The thymic nurse cells in the cortico-medullary junction express cytokeratin 5 (K5) and cytokeratin 8 (K8), whereas the ones in the cortex express only cytokeratin 8." Seems this is a mix of two populations. Should terms be created for these two populations? Many thanks

Given the different expression profiles and locations, it may make sense to create separate classes for cortical TNC and cortico-medullary TNC. 
PMID:20035931 also makes the connection specifically between the cortico-medullary TNCs and thymic epithelial progenitors:

"...  All TNCs, whether in culture or in vivo, were found to express the pH91-specific antigen (Figure 3) [13]. A subset of these pH91+ cells expressed the transcription factor p63 (Figure 4). Using freshly isolated cells, we also showed that nearly a quarter of TNCs are pH91+K8+K5+ cells (Figure 2). Our in vivo studies show that the K8+K5+ double positive cells with the unique structure of TNCs to be located in the cortico-medullary junction. The thymic epithelial progenitor cell type has been reported to reside in the cortico-medullary junction and to express both K8 and K5 cytokeratins and p63 [25; 26]. Several studies show thymic epithelial progenitor cells to be able to regenerate an entire functional thymus when transplanted under the kidney capsule [23; 30; 31]. Our data show a subset of TNCs located in the cortico-medullary junction express the reported characteristics of thymic epithelial progenitors. ..."

**Comment by paulacalipho** [comment]
Hi, @bvarner-ebi  

You would create "Thymic nurse cell" and the two cell types "TNC cortico-medullary junction K5/K8" and "TNC cortex K8" as child of "Thymic nurse cell" or only the two child terms?

According to PMID:20035931 "TNC cortico-medullary junction K5/K8" are "thymic epithelial progenitor cells"? May be this cell type is related to corticomedullary thymic epithelial cell (CL:0009070) ?

**Comment by bvarner-ebi** [comment]
Hi @paolaroncaglia, since you have been involved in creating new terms related to thymus cells, do you have any comments on this request? Particularly, do you have a comment on whether a 'thymic nurse cell' should be one new class or broken into separate classes for cortical and corticomedullary types? I think a case could be made for either option, but would one approach be preferred?

**Comment by paolaroncaglia** [comment]
Hi @addiehl ,
Would you be able to provide feedback on this please? We can take care of the edits. Thanks in advance!

**Comment by paolaroncaglia** [comment]
@bvarner-ebi and @paulacalipho one thing I recall from working on thymus cell types for the ASCT+B tables is that e.g. for subtypes of double-negative thymocytes there were significant differences in markers between human and mouse. The parent cell type for this request ('epithelial cell of thymus') is, rightfully, species-agnostic. The [Wikipedia entry that Paula referenced](https://en.wikipedia.org/wiki/Thymic_nurse_cell), based on its bibliography, includes a mix of human and mouse studies. The [paper that Bradley quoted](https://www.ncbi.nlm.nih.gov/pmc/articles/PMC2830717/) is based on mouse cells only. Unless unequivocal evidence is available that the same markers (human/mouse homologs) are found in each population, I'd keep that information in definition gloss or rdfs:comment, rather than use it to support subclasses. As for using the thymus location to support subclasses or not, at a quick glance again that partly depends on the balance between having a single term that's more broadly applicable (to other mammalian species for example) vs. having two granular terms as long as you can support them adequately. It's not even clear to me if nurse cells are _always_ part of both thymus cortex and cortico-medullary junction, so the less risky option would be to have one class of TNC as part of thymus, but I haven't delved into the literature.

**Comment by bvarner-ebi** [comment]
Thanks for the insight, @paolaroncaglia! Based on your feedback, it seems like creating a single new class for TNC seems appropriate. We can get more granular in the future as needed and if more specific literature is found.

**Comment by paulacalipho** [comment]
Hi @paolaroncaglia , Hi @bvarner-ebi , many thanks for your input and creating this term, Paula
