### ISSUE TITLE
[Merge] Merging two bronchioalveolar stem cell terms

### ISSUE THREAD

**Issue by JoshuaFortriede** [obophenotype/cell-ontology#1443]
**CL term (ID and Label)**
CL:1001566
bronchioalveolar stem cells

**Reason for deprecation**
Duplicate

**Term to be merged with (ID and Label)**
CL:0002638
bronchioalveolar stem cell

**Comment by paolaroncaglia** [comment]
@JoshuaFortriede good catch. FYI, it looks like CL:0002638 was added by Terry upon [Chris' request](https://github.com/obophenotype/cell-ontology/issues/308), but CL:1001566 may also have been added by Chris via automatic generation as per https://github.com/obophenotype/cell-ontology/blob/master/src/ontology/cl-idranges.owl.
I'm sure there's a check in CL to prevent identical primary labels, but this one wasn't caught because CL:1001566 is pluralised, which is not SOP so an unlucky occurrence. Looking for other occurrences of "cells" in primary labels, there's also CL:2000091 'endometrial microvascular endothelial cells' (generated via TermGenie) that should be made singular, please.
There may be other labels that don't end with "cell" and are not singular, but hopefully not. Thank you.

**Comment by paolaroncaglia** [comment]
@JoshuaFortriede @shawntanzk 

> do you want me to go ahead and do this initial merge or should someone else handle it?

Sure, please go ahead and do a pull request, but first please check the merge procedure with @shawntanzk, as he's been working on an SOP with @dosumis . Thank you for handling this. You may want to remove Nicole's assignment in that case.

**Comment by shawntanzk** [comment]
@JoshuaFortriede that would be great! and I would be super grateful if you could test out the documents here https://github.com/obophenotype/cell-ontology/pull/1448 for it (sorry its still in a PR format, but should be easy enough to navigate) thanks!
