### ISSUE TITLE
[Synonym] exchange the ontology term label for an existing synonym

### ISSUE THREAD

**Issue by jychien** [obophenotype/cell-ontology#1460]
**CL term**
CL:0000653: https://www.ebi.ac.uk/ols/ontologies/cl/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FCL_0000653
There is an associated Term Not Found link: http://purl.obolibrary.org/obo/CL_0000653

**Issue**
Requesting that the ontology term label be "podocyte", as this is the term currently used by the community to name these cell types. "glomerular visceral epithelial cell" would then be a synonym. Here are a few papers:
-https://doi.org/10.1101/2021.07.28.454201
-https://doi.org/10.1038/s41467-021-22368-w
-https://doi.org/10.1101/2021.10.10.463829
-https://dx.doi.org/10.1126%2Fscience.aat5031

**Comment by nicolevasilevsky** [comment]
there is a comment on this class:
GO has podocyte as a related synonym due to concern this may refer to more than one cell type. However, this did not turn up in my search. If podocyte does refer to more than one cell type, then we should classify the synonym to 'related'[tfm].

Does anyone have any objections to renaming this?
@dosumis @addiehl @paolaroncaglia etc.

**Comment by paolaroncaglia** [comment]
Hi @jychien ,

> There is an associated Term Not Found link: http://purl.obolibrary.org/obo/CL_0000653

That must have been due to a temporary glitch in Ontobee, the link is active right now.

**Comment by paolaroncaglia** [comment]
@dosumis @nicolevasilevsky and cc @bvarner-ebi as he's been looking at this kidney domain
I don't have any objection to renaming CL:0000653 'glomerular visceral epithelial cell' to 'podocyte' (currently an exact synonym).
Note that we also have CL:0000391 'podocyte (sensu Diptera)', but hopefully that term should not be an issue because it does not have "podocyte" as a synonym. However,
- [ ] Perhaps add exact synonyms to CL:0000653 "kidney podocyte", "renal podocyte" to help disambiguate?
- [ ] I'd also remove the old comment from CL:0000653, and add a seeAlso annotation pointing to this ticket. Thanks.

**Comment by bvarner-ebi** [comment]
@paolaroncaglia, thanks for adding me to this ticket. FYI, there is a related open PR (#1401) that will be merged once the next Uberon release is published.

I'd be happy to make the changes you suggest. @jychien, @dosumis, @nicolevasilevsky, kindly add your comments if you have any concerns.

**Comment by nicolevasilevsky** [comment]
Please go ahead @bvarner-ebi, thank you!

**Comment by jychien** [comment]
@nicolevasilevsky, @dosumis, @bvarner-ebi , @paolaroncaglia 
Thank you, everyone, for the quick response and update of the term label.

**Comment by bvarner-ebi** [comment]
Thanks for the contribution, @jychien. A few additional notes at PR #1474.

**Comment by bvarner-ebi** [comment]
CL:0000653 (now labeled podocyte) has been updated as detailed in PR #1474. Thanks for all the feedback and these updates should be reflected in the next CL release.
