### ISSUE TITLE
[NTR] fallopian tube secretory epithelial cell

### ISSUE THREAD

**Issue by paulacalipho** [obophenotype/cell-ontology#1475]
**Preferred term label:**
fallopian tube secretory epithelial cell

**Synonyms**
oviduct secretory epithelial cell
uterine tube secretory epithelial cell

**Definition**
Fallopian tube secretory epithelial cell is one of the three cell types of the fallopian tube epithelium. The two other cell types of the fallopian tube epithelium are the ciliated cells and the intercalary cell, or peg cells. The secretory cell has approximately the same height as the ciliated cell and is usually a more narrow columnar cell. The nucleus is ovoid and perpendicular to the long axis of the cell. The chromatin is more dense and the nucleolus smaller than that seen in the ciliated cell. [https://www.proteinatlas.org/learn/dictionary/normal/fallopian+tube]

**Parent cell type term:**
CL:1001591 (oviduct glandular cell)

**What is the anatomical structure that the cell is a part of?**
UBERON:0003889 (fallopian tube)

**Your nano-attribution (ORCID)**
0000-0002-0819-0473

**Comment by bvarner-ebi** [comment]
Hi @paulacalipho, thank you for the new term request. 
The other two cell types of the fallopian tube epithelium mentioned in your definition currently do not appear in CL (references to these other cell types also appear in the parent cell type definition). Would you like to provide details on those two other cell types in order to add them? This is not necessary, and I will defer to your preference.

**Comment by paulacalipho** [comment]
Hi @bvarner-ebi I can work on definitions for these two cell types and come back to you asap

**Comment by bvarner-ebi** [comment]
Thank you, @paulacalipho.
In the meantime, I have added CL:4030006 fallopian tube secretory epithelial cell to the Cell Ontology.

The definition:
An epithelial cell that is part of the fallopian tube epithelium that secretes mucous fluid and oviduct-specific products through the stimulation of estrogen and luteinizing hormone. The fallopian tube secretory cell has approximately the same height as the ciliated cell and is usually a more narrow columnar cell. The nucleus is ovoid and perpendicular to the long axis of the cell. The chromatin is more dense and the nucleolus smaller than that seen in the ciliated cell.

Annotated as a comment:
The other cell types of the fallopian tube epithelium include the ciliated cell and the intercalary cell, or peg cell. The fallopian tube secretory epithelial cell type has been implicated as a source of high-grade serous ovarian carcinoma.

Let me know if you have any questions or concerns.

**Comment by paulacalipho** [comment]
@bvarner-ebi Perfect, many thanks

**Comment by paulacalipho** [comment]
@bvarner-ebi Sorry for the late notice, but instead of part of UBERON:0003889 (fallopian tube), should be better consider part of ciliated columnar oviduct epithelium  UBERON:0007589, as just requested for "fallopian tube ciliated cell"?

**Comment by bvarner-ebi** [comment]
Hi @paulacalipho, thank you for the question. 
Do you have a source to support that the 'fallopian tube secretory epithelial cell' is part of the 'ciliated columnar oviduct epithelium'? Otherwise, we could make it part of the less specific UBERON:0004804 'oviduct epithelium'.

**Comment by paulacalipho** [comment]
@bvarner-ebi As "fallopian tube secretory epithelial cell'' is part of the "fallopian tube epithelium" that have also ciliated cells, I assumed that is a ciliated epithelium. But I may be wrong and would be better to make part of UBERON:0004804 'oviduct epithelium'.

**Comment by bvarner-ebi** [comment]
@paulacalipho, my hesitation is not knowing if this cell type is always found in what would be classified as ciliated columnar oviduct epithelium since there is variation in the epithelium of the oviduct both spatially and temporally. 

Per PMID:[25117646](https://www.ncbi.nlm.nih.gov/pubmed/25117646):

The ciliated cells are mainly found on the apex of the mucosal folds [7], mostly in the fimbria (over 50 %) and less commonly in the isthmus (less than 35 %) [5, 6, 8]. Cilia extend from the apical surface of the ciliated cells into the lumen of the tube and are about 10 μm long and 0.25 μm in diameter [9]. Secretory cells are non-ciliated cells and contain apical granules that produce the tubular fluid. The least common cell type are intercalated cells, also known as peg cells whose function and even existence as a discrete cell type is a matter of debate. While some authors consider them a distinct type of secretory cells whose contents have been extruded with resulting collapsed cytoplasm [10], others consider them as merely representing a morphological variant of the classic secretory cells [11, 12]. Tubal epithelium undergoes cyclical changes in response to ovarian steroids which can be evident as a higher percentage of ciliated cells in the follicular phase, with gradual transition into a secretory cell-dominant pattern in the luteal phase of the cycle [10, 12].

**Comment by paulacalipho** [comment]
@bvarner-ebi OK, in that case is better relate it to UBERON:0004804 'oviduct epithelium'. In addition the creation of the peg cells may not be recommended

**Comment by bvarner-ebi** [comment]
Thanks for the feedback, @paulacalipho.

Since this term is a subclass of 'oviduct glandular cell', it being part of the 'oviduct epithelium' is already inferred, so I don't think any change is needed:

![Screenshot 2022-03-08 at 07 37 09](https://user-images.githubusercontent.com/95643797/157239550-da77c58c-e290-4df9-8c79-e80dbad1c4da.png)
