### ISSUE TITLE
has_(not)_completed axioms on immune cells might not be accurate

### ISSUE THREAD

**Issue by shawntanzk** [obophenotype/cell-ontology#1490]
See https://github.com/oborel/obo-relations/issues/574
I can't remember why this was the case exactly, but @bpeters42 brought this up - perhaps he can explain a bit? 

The logical axioms I gave as examples are: 
memory T cell has_completed some 'memory T cell differentiation'
immature T cell has_not_completed some 'T cell selection'

**Comment by addiehl** [comment]
See my comment about this at https://github.com/oborel/obo-relations/issues/574

**Comment by addiehl** [comment]
memory T cell has_completed some 'memory T cell differentiation' does seem circular, but we went to that formulation because the CD45RO isoform that was at one point considered a reliable marker for memory T cells in human and primates, does not appear on so-called TEMRA cells (T effector memory CD45RA-positive T cells), and does not work as a marker for memory T cells in mice either.

'memory T cell' equivalent to
'mature T cell'
 and ('has characteristic' some 'increased life span')
 and ('output of' some 'T cell activation involved in immune response')
 and ('output of' some 'memory T cell differentiation')

**Comment by shawntanzk** [comment]
Closing this, please refer to the linked RO ticket instead
