### ISSUE TITLE
renal interstitial pericyte - add textual definition and revise logical definition

### ISSUE THREAD

**Issue by dosumis** [obophenotype/cell-ontology#1528]
* Currently has very broad logical definition: pericyte and part_of some kidney.  Should have some restriction to kidney interstitium
* Needs textual definition - potential references @emquardokus to add
* Relationship to mesangial cells is confusing
   * Only some mesangial cells defined as pericytes in textual definitions. 
<img width="353" alt="image" src="https://user-images.githubusercontent.com/112839/161103379-b8fdf1a3-b18a-4a4f-819f-bcc72c2fda31.png">
<img width="350" alt="image" src="https://user-images.githubusercontent.com/112839/161103464-efcfafe1-ee86-45fb-83de-ed828412dddb.png">

**Comment by bvarner-ebi** [comment]
For reference:

The renal interstitium is defined as the intertubular, extraglomerular, extravascular space of the kidney. It is bounded on all sides by tubular and vascular basement membranes and is filled with cells, extracellular matrix, and interstitial fluid ([1](https://cjasn.asnjournals.org/content/10/10/1831#ref-1)). Its distribution varies within the kidney; it accounts for approximately 8% of the total parenchymal volume in the cortex and up to 40% in the inner medulla ([6](https://cjasn.asnjournals.org/content/10/10/1831#ref-6),[7](https://cjasn.asnjournals.org/content/10/10/1831#ref-7)). The term “renal interstitium” is often inadequately used to refer to the peritubular interstitium (the space between tubules, glomeruli, and capillaries); the periarterial connective tissue and the extraglomerular mesangium are considered specialized interstitia ([1](https://cjasn.asnjournals.org/content/10/10/1831#ref-1)). It is debated whether microvessels and capillaries, which are located within the peritubular space, are actually part of the renal interstitium or just run through it ([1](https://cjasn.asnjournals.org/content/10/10/1831#ref-1)). Furthermore, lymphatics are considered interstitial constituents ([1](https://cjasn.asnjournals.org/content/10/10/1831#ref-1)). The tubular interstitium in the cortex and medulla differ with regard to their cellular constituents, extracellular matrix composition, relative volume, and endocrine function, justifying the consideration of cortical and medullary interstitium as separate entities.

DOI: https://doi.org/10.2215/CJN.00640114

**Comment by bvarner-ebi** [comment]
Proposed solution:

[ ] Change EA from:

'pericyte cell'
 and ('part of' some kidney)

to

'pericyte cell'
 and ('part of' some 'kidney interstitium')

Note that there seems to be debate whether this should invoke a 'part of' or 'located in' relationship as suggested in the reference above ("It is debated whether microvessels and capillaries ... are actually part of the renal interstitium or just run through it ([1](https://cjasn.asnjournals.org/content/10/10/1831#ref-1))")

[ ] Add textual definition:
A pericyte cell located in the kidney interstitium. 
Since 'pericyte cell' and 'kidney intersitium' have text definitions in their respective terms, the above may be sufficient. @emquardokus, what do you think? Are there any defining features of this cell type you think we should add to the text definition?

[ ] Per https://en.wikipedia.org/wiki/Extraglomerular_mesangial_cell:
"Extraglomerular mesangial cells ... are light-staining [pericytes](https://en.wikipedia.org/wiki/Pericytes) in the [kidney](https://en.wikipedia.org/wiki/Kidney) found outside the [glomerulus](https://en.wikipedia.org/wiki/Glomerulus_(kidney))..."

https://en.wikipedia.org/wiki/Intraglomerular_mesangial_cell#cite_note-2:
"Mesangial cells are [macrophages](https://en.wikipedia.org/wiki/Macrophage)[[1]](https://en.wikipedia.org/wiki/Intraglomerular_mesangial_cells#cite_note-1) and resemble [pericytes](https://en.wikipedia.org/wiki/Pericyte).[[2]](https://en.wikipedia.org/wiki/Intraglomerular_mesangial_cells#cite_note-2)"

https://en.wikipedia.org/wiki/Glomerulus_(kidney)#Mesangium:
"[Intraglomerular mesangial cells](https://en.wikipedia.org/wiki/Intraglomerular_mesangial_cells). They are not part of the filtration barrier but are specialized [pericytes](https://en.wikipedia.org/wiki/Pericytes) that participate in the regulation of the filtration rate by contracting or expanding..."

In CL, 'glomerular mesangial cell' has exact synonym 'intraglomerular mesangial cell'.

https://doi.org/10.1016/B978-0-12-815876-0.00015-2:
"Mesangial cells function as pericytes for the glomerular endothelium."

https://www.ncbi.nlm.nih.gov/pmc/articles/PMC4074211/:
"Mesangial cells are specialized pericyte/smooth muscle cells that surround and constrain the vascular network within the glomerulus of the kidney. They are derived from the stromal mesenchyme, a progenitor population distinct from nephron stem cells. Whether mesangial cells have a distinct origin from vascular smooth muscle cells (VSMCs) and the pathways that govern their specification are unknown."

Given the above, the current modelling may be justified, although the relationship between mesangial cells and pericytes does not seem absolute: ("is a" vs "resembles" vs "function as"). Perhaps we leave as-is for now.

@emquardokus, can you check with the kidney SME if the above seems like a reasonable solution?

**Comment by dosumis** [comment]
Do this first & commit:

> 'pericyte cell'
> and ('part of' some kidney)
> 
> to
> 
> 'pericyte cell'
> and ('part of' some 'kidney interstitium')

**Comment by emquardokus** [comment]
@bvarner-ebi  citation
STOCKAND, JAMES D., and STEVEN C. SANSOM. 1998. “Glomerular Mesangial Cells: Electrophysiology and Regulation of Contraction.” Physiological Reviews 78 (3): 723–44. https://doi.org/10.1152/physrev.1998.78.3.723.
