### ISSUE TITLE
NTR: oxytocin receptor interneuron

### ISSUE THREAD

**Issue by GoogleCodeExporter** [obophenotype/cell-ontology#153]
```
http://neurosciencenews.com/neuroscience-oxytocin-genetics-neurons-1416/

syn: OxtrINs

def: interneuron and capable_of some (GO:oxytocin receptor activity)
```

Original issue reported on code.google.com by `cmung...@gmail.com` on 9 Oct 2014 at 7:42

**Comment by shawntanzk** [comment]
term: oxytocin receptor interneuron (Mus musculus) 

def: An interneuron located in the mouse cerebral cortex that express the oxytocin receptor. These interneurons also express somatostatin (sst). 

parent term: interneuron 

axioms: 
'has soma location' some 'cerebral cortex' 
'capable of' some 'gamma-aminobutryic acid secretion, neurotransmission'
'expresses' some 'somatostation'
'expresses' some 'oxytocin receptor' (PR:000001635) <- needs to be imported

Notes:
I suggest we make this term specifically to mouse as their experiments were done on mouse and I'm not sure how generalisable they are. Happy to change it more general if appropriate. 
I've put it as a cerebral cortex interneuron as the paper similar looked specifically at the cerebral cortex 
This would automatically classify it as a SST GABAergic cortical interneuron - something we have created for BDS - interesting how this did not get mapped to a transcriptomic cluster. This could be due to a few things imo:
1) it is a subcluster that didn't get pick up in heirachical clustering 
2) it is a cell type that cuts across transcriptomic clusters
3) it didnt get mapped as the annotations are manually done 
What worries me is that this might result in duplicate term called different names (I've done some searches and dont see this obviously at least). Happy to still add the term, might be useful for peoples annotations if they look at oxtrINs, but probably want some input from someone more experienced to this issue before I do. @cmungall @dosumis
