### ISSUE TITLE
Should "lipophage" be a synonym of CL:0000891 'foam cell'?

### ISSUE THREAD

**Issue by paola-scibite** [obophenotype/cell-ontology#1589]
@addiehl please (or anyone who'd like to help):
Is "lipophage" the same as "foam cell"?
CL:0000891 'foam cell': "A type of cell containing lipids in small vacuoles and typically seen in atherolosclerotic lesions, as well as other conditions. [ GOC : add ]"
Wikipedia [says](https://en.wikipedia.org/wiki/Foam_cell) that foam cells are also called lipid-laden macrophages, and SNOMED [says](https://www.ebi.ac.uk/ols/ontologies/snomed/terms?iri=http%3A%2F%2Fsnomed.info%2Fid%2F13901007) that 'Fat-laden macrophage (cell)' has altLabel lipophage. Pubmed hits for "lipophage" are old and not easily accessible.
Thanks,
Paola

**Comment by lubianat** [comment]
This relatively recent: https://cap.objects.frb.io/documents/2018-hematology-clinical-microscopy-glossary.pdf 

I'd vote for yes, it is used as a synonym (at least in some contexts)

**Comment by lubianat** [comment]
![image](https://user-images.githubusercontent.com/7917951/169087291-66626a6f-64dd-42b0-a8fb-42539c3943f3.png)

**Comment by addiehl** [comment]
We should add "lipophage" as a exact synonym for 'macrophage derived foam cell' CL:0000517, rather than its parent 'foam cell' because 'smooth muscle cell derived foam cell' CL:0000892 is also a child of 'foam cell' and does not develop a monocyte/macrophage ([PMID:6136115](https://pubmed.ncbi.nlm.nih.gov/6136115/)).

**Comment by addiehl** [comment]
Note that the Wikipedia article on "Foam Cell" does not discuss smooth muscle derived foam cells, and thus is an incomplete source of knowledge on foam cells.

**Comment by lubianat** [comment]
That is great, Alex. I'll try and update Wikipedia on foam cells. If there are any articles/resources that you think it should be included there too, just let me know.

**Comment by addiehl** [comment]
Hi Tiago.  The 2019 article above is a good start, but of course there are many more, such as this 2022 [review](https://www.frontiersin.org/articles/10.3389/fcvm.2022.845942/full).  [PMID:34345929](https://pubmed.ncbi.nlm.nih.gov/34345929/), 2021, and [PMID:33096029](https://pubmed.ncbi.nlm.nih.gov/33096029/) also look interesting from the abstracts, though my institution does not have these articles available immediately to me.  However [this article](https://academic.oup.com/cardiovascres/article/117/11/2326/6130794?login=false) and [this article](https://bpspubs.onlinelibrary.wiley.com/doi/10.1111/bph.14779) are open access with good information about foam differentiation from smooth muscle cells.

These were all found using "smooth muscle foam cell" in PubMed.  I've only looked at the first 60/382 results, but clearly a lot has been published on these cell types since I worked on the foam cells terms many years ago.  We should consider adding [PMID:30664015](https://pubmed.ncbi.nlm.nih.gov/30664015/) or another one of these references to 'smooth muscle cell derived foam cell', which does not currently have any PMID associated.

In any case, you are brave to take on editing the Wikipedia entry!

**Comment by paolaroncaglia** [comment]
@lubianat @addiehl thank you both for your feedback!
I'll add "lipophage" as a exact synonym for 'macrophage derived foam cell' CL:0000517, and I'll leave it to Tiago to edit the Wikipedia entry on foam cells. I'm assigning this ticket to both of us accordingly.

**Comment by lubianat** [comment]
Thanks Alex! I just added a line there about the smooth-muscle derived foam cells (I do not know enough about them to make larger modifications). And agreed, it would be good to have a reference in the CL entry.

**Comment by paolaroncaglia** [comment]
@addiehl @lubianat I will also add [PMID:30664015](https://pubmed.ncbi.nlm.nih.gov/30664015/) to 'smooth muscle cell derived foam cell'

**Comment by paolaroncaglia** [comment]
@lubianat @addiehl I did my edits, and Tiago said he edited the Wikipedia entry, so I'll close.
