### ISSUE TITLE
unsatisfiable class: lymph node marginal reticular cell is part_of an immaterial entity

### ISSUE THREAD

**Issue by balhoff** [obophenotype/cell-ontology#1636]
This came up in a GO issue (there is an explanation there): https://github.com/geneontology/go-ontology/issues/23510#issuecomment-1158056090

The Ubergraph pre-release coherency check missed this because it turns out there are a few CARO-to-BFO bridge axioms found only in an RO import. I've since added this import to the check: https://github.com/INCATools/ubergraph/runs/6926464224?check_suite_focus=true

**Comment by shawntanzk** [comment]
[lymph node marginal reticular cell](http://purl.obolibrary.org/obo/CL_0009103) SubClassOf [part of](http://purl.obolibrary.org/obo/BFO_0000050) some [subcapsular sinus of lymph node](http://purl.obolibrary.org/obo/UBERON_0005463)
[subcapsular sinus of lymph node](http://purl.obolibrary.org/obo/UBERON_0005463) EquivalentTo [anatomical space](http://purl.obolibrary.org/obo/UBERON_0000464) and ([part of](http://purl.obolibrary.org/obo/BFO_0000050) some [lymph node](http://purl.obolibrary.org/obo/UBERON_0000029)) and ([adjacent to](http://purl.obolibrary.org/obo/RO_0002220) some [cortex of lymph node](http://purl.obolibrary.org/obo/UBERON_0002006)) and ([adjacent to](http://purl.obolibrary.org/obo/RO_0002220) some [capsule of lymph node](http://purl.obolibrary.org/obo/UBERON_0002194))

This is the issue I think - instead of part_of sinus, perhaps adjacent_to?

**Comment by matentzn** [comment]
@shawntanzk can we hotfix this now in whatever way, I can run a new release and we make a new issue to figure out the correct modelling? All worries should be dwarfed by unsats.

Since you define the sinus of lymph node as immaterial, it does not make sense to say its part of something material. It could be contained in it, or adjacent to it, or located in probably?

**Comment by shawntanzk** [comment]
I'll change it to adjacent to for now -> located in wont work due to range that is imported into CL 
```
'independent continuant'
 and (not ('spatial region'))
```

**Comment by dosumis** [comment]
The correct relation is located_in (we need to add this here https://github.com/obophenotype/cell-ontology/blob/master/docs/relations_guide.md#recording-location).  We use this in multiple places for cells --> spaces especially sinuses.   The range is a confusing legacy of obsolete BFO concepts and should be fixed in RO.   It has no logical consequences under ELK reasoning.

Please change from adjacent_to ASAP, as this will cause fails for HubMap and scAtlas.
