### ISSUE TITLE
[NTR] peripheral blood lymphocyte

### ISSUE THREAD

**Issue by kalpanaps** [obophenotype/cell-ontology#1655]
Note - please check that the term does not already exist (check OLS: https://www.ebi.ac.uk/ols/ontologies/cl)

**Preferred term label**: peripheral blood lymphocyte

**Synonyms** (add reference(s), please)

**Definition** (free text, with reference(s), please. PubMed ID format is PMID:XXXXXX): Lymphocyte subsets including T cells (CD3+), (B) B cells (CD19+) and (C) NK cells (CD3− CD56+) PMID:31092833

**Parent cell type term** (check the hierarchy here https://www.ebi.ac.uk/ols/ontologies/cl): Lymphocyte (CL:0000542)

**What is the anatomical structure that the cell is a part of?** (check Uberon: https://www.ebi.ac.uk/ols/ontologies/uberon)

**Your ORCID**:  https://orcid.org/0000-0003-2534-198X

**Additional notes or concerns**

**Comment by bvarner-ebi** [comment]
Thank you for the new term request, @kalpanaps and for the feedback, @addiehl.

After skimming the reference, I am not sure if the text definition is appropriate since it seem to refer to specific cell types that were arbitrarily highlighted in the study. Could there be other subsets that are 'peripheral blood lymphocytes' that are not mentioned in this text definition? @kalpanaps, can you confirm or advise if I am misunderstanding?

@addiehl, would this EA also capture lymphocytes that are in blood but not part of acral / peripheral circulation? It seems like 'blood' == 'peripheral blood' in the ontology. Is that intended?

**Comment by addiehl** [comment]
Peripheral blood is called peripheral presumably because it is taken most often from a peripheral location of the body, such as an arm.  Blood travels rather quickly through the circulatory system, and I believe the assumption is that the composition of blood extracted at a peripheral location is roughly similar to blood throughout the body, apart from oxygen content.  While there are mechanisms for lymphocytes to move into and out of the blood, most researchers seem to assume that the relative abundance and levels of lymphocyte subsets in blood taken at a peripheral location are representative of the blood as a whole.

**Comment by bvarner-ebi** [comment]
Thanks, @addiehl. I'm thinking from a clinical perspective where there is a distinction in central vs peripheral circulation (central line / PICC line vs peripheral IV, blood cultures from peripheral vs central lines, peripheral blood smear, drug concentrations before first pass metabolism, cord blood, etc). If scientists don't make a distinction between central vs peripheral blood, then the EA sounds appropriate.

**Comment by bvarner-ebi** [comment]
@kalpanaps, is it agreeable to define your new term as follows:

text defintion:
"A lymphocyte located in blood."

equivalence axiom:
lymphocyte and 'part of' some blood

**Comment by bvarner-ebi** [comment]
Hi, @kalpanaps,

Thank you for your contribution.
The following 2 terms have been added to CL and will be available in the next CL release.

CL:4030029 'blood lymphocyte'
A lymphocyte located in blood.

CL:4030030 'peripheral blood lymphocyte'
A blood lymphocyte located in the flowing, circulating blood of the body.

**Comment by dosumis** [comment]
@bvarner-ebi  - please could you add a review of these terms for the next CL call.  A couple of people at the CZI meeting brought up the issue of very general terms like this lacking or being very incomplete for subclasses.

**Comment by addiehl** [comment]
That's unfortunate, since there are extensive T and B cell hierarchies available for their use in annotation. It would be a mistake to specify that these cell types are subclasses of 'peripheral blood lymphocyte', since T and B cells (and other immune cell types) can be found in the blood, lymph, lymph nodes, spleen, and other lymphoid tissues, as well as in areas of inflammation at different points in their lifespan.

**Comment by bvarner-ebi** [comment]
> @bvarner-ebi - please could you add a review of these terms for the next CL call. A couple of people at the CZI meeting brought up the issue of very general terms like this lacking or being very incomplete for subclasses.

Will those with concerns be attending the CL meeting? There was a fair amount of discussion with @addiehl around entering these terms at the time of their addition, and I agree that these new terms are not ideal candidates as parent classes for all the types of lymphocytes that may appear in peripheral blood.
