### ISSUE TITLE
[NTR-cxg] BEST4+ intestinal epithelial cell

### ISSUE THREAD

**Issue by rachadele** [obophenotype/cell-ontology#1695]
**Preferred term label**
BEST4+ intestinal epithelial cell

**Synonyms** (add reference(s), please)

**Definition** (free text, with reference(s), please. PubMed ID format is PMID:XXXXXX)
An absorptive epithelial cell of the human intestine expressing Bestrophin 4 calcium-activated ion channels. 
PMID:24223998
PMID:35176508

**Parent cell type term** (check the hierarchy here https://www.ebi.ac.uk/ols/ontologies/cl) 
CL:0000677

**What is the anatomical structure that the cell is a part of?** (check Uberon: https://www.ebi.ac.uk/ols/ontologies/uberon)
intestinal epithelium UBERON:0001277

**Your ORCID**
0000-0002-7431-4139

**Additional notes or concerns** If there are markers that uniquely identify the cell type in a particular species, they can be added here.

**Comment by bvarner-ebi** [comment]
Hi @rachadele, can you clarify if you intend for this class to only represent a cell type in **humans** as noted in your definition? I see the reference paper is focused on humans, but if this cell type exists in other species or genera, we can remove the word "human" from the definition and not worry about taxon restrictions.

**Comment by bvarner-ebi** [comment]
Hi @rachadele, checking in to see if you have feedback on my comment immediately above. Once clarified, I can move forward with adding this new cell type.

**Comment by lubianat** [comment]
@bvarner-ebi As far as I know, they are not known in mice. 

How about having 2 terms, one more neutral, without the taxonomic restriction, and a subclass restricted to humans?

**Comment by rachadele** [comment]
Yes, it is intended to be a human cell type! Sorry for the late response.

**Comment by bvarner-ebi** [comment]
> @bvarner-ebi As far as I know, they are not known in mice.
> 
> How about having 2 terms, one more neutral, without the taxonomic restriction, and a subclass restricted to humans?

Thanks for the feedback, @lubianat. My understanding is that it is discouraged to create new classes that would have only one child. (@shawntanzk, is my assumption correct)? Since there is also no evidence supplied that the cell type exists in other species, I am hesitant to create a taxon-agnostic class without supporting dbxrefs.

**Comment by shawntanzk** [comment]
> My understanding is that it is discouraged to create new classes that would have only one child. (@shawntanzk, is my assumption correct)?

Yups. Chris Mungall wrote a blog about this - https://douroucouli.wordpress.com/2022/01/04/ontotip-avoid-the-single-child-anti-pattern/ 

> How about having 2 terms, one more neutral, without the taxonomic restriction, and a subclass restricted to humans?

Would ideally like to avoid this too. My preference with this would be instead to have taxon GCIs rather than a subclass restricted to humans if need be - very easily bloats an ontology if we want everything to have specific terms for species

**Comment by rachadele** [comment]
thank you!

**Comment by rachadele** [comment]
hi there– when will the release with this term be published?

**Comment by shawntanzk** [comment]
it should be in the latest release, do let us know if you don't see it and we can track down why :)

**Comment by rachadele** [comment]
I do not see it!

**Comment by shawntanzk** [comment]
I've just checked our release (cl.owl at least), it is in there. Perhaps you are trying to find it in OLS? if that's the case, this is due to OLS not having updated CL release - they are working on it, I can't fully rmbr the reason, but their automated system is down, making it tricky. Perhaps consider using ontobee for now - CL purls redirect there anyway (http://purl.obolibrary.org/obo/CL_4030026)

**Comment by rachadele** [comment]
thank you! I requested this term for a cellxgene submission, but it's causing the submission to fail validation. i'm guessing maybe their validator tool pulls valid ontologies from OLS since it doesn't seem to recognize this term. I will have to ask their devs about it :)

**Comment by shawntanzk** [comment]
btws just a small thing, but our preference is for people to pull the ontology through our purl system (http://purl.obolibrary.org/obo/cl.owl) - it's something that I'm supposed to tell people using it. Using the purl = if we change anything (eg how we do releases), it won't affect your pipelines. If your devs are going to change where they pull the ontology from, maybe suggest that to them :) thanks!
