### ISSUE TITLE
Updated telocyte definition

### ISSUE THREAD

**Issue by anitacaron** [obophenotype/cell-ontology#1718]
Updated telocyte ID to CL:0017004; however, I am submitting a ticket to CL to update the definition, and remove the **has exact synonym** to these terms since telocytes are not only located in the intestine and the "interstitial Cajal cell" is associated with intestines.  
   interstitial Cajal cell-like cell
    ICLC
    interstitial Cajal-like cell

See Nicolescu, Mihnea I., Mugurel C. Rusu, Liliana M. Voinea, Alexandra D. Vrapciu, and Raluca I. Bâră. “Lymphatic Lacunae of the Human Eye Conjunctiva Embedded within a Stroma Containing CD34+ Telocytes.” Journal of Cellular and Molecular Medicine 24, no. 15 (August 1, 2020): 8871–75. https://doi.org/10.1111/jcmm.15354.

_Originally posted by @emquardokus in https://github.com/obophenotype/asct-b_validation/issues/40#issuecomment-1279268356_

**Comment by anitacaron** [comment]
@bvarner-ebi, there's already a [telocyte in CL](https://www.ebi.ac.uk/ols/ontologies/cl/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FCL_0017004). It was unmapped into the ASCT+B table. It should be removed from your priority new cell types list.

**Comment by emquardokus** [comment]
@bvarner-ebi @anitacaron generic telocyte is indeed in CL; however, the definition states it's in a specific location, so that is what needs to be altered because they indeed exist all over the body.  The instance in our ASCT+B table was in the eye, so I was resistant to adding the generic CL ID because the definition doesn't fit with eye location.
Here are some additional references that indicate widespread locations across human body (but there are also mice references we could add if needed).
1)Gives some better history and definition: PMID: [31311805](https://pubmed.ncbi.nlm.nih.gov/31311805) Kondo, Ayano, and Klaus H. Kaestner. “Emerging Diverse Roles of Telocytes.” Development (Cambridge, England) 146, no. 14 (July 16, 2019). https://doi.org/10.1242/dev.175018.
2) Gives a definition: Condrat, Carmen Elena, Mădălina Gabriela Barbu, Dana Claudia Thompson, Cezara Alina Dănilă, Andreea Elena Boboc, Nicolae Suciu, Dragoș Crețoiu, and Silviu Cristian Voinea. “Chapter One - Roles and Distribution of Telocytes in Tissue Organization in Health and Disease.” In Tissue Barriers in Disease, Injury and Regeneration, edited by Nikolai V. Gorbunov, 1–41. Elsevier, 2021. https://doi.org/10.1016/B978-0-12-818561-2.00001-1.

**Comment by bvarner-ebi** [comment]
@emquardokus, can you point to where in the CL definition it states it is in a specific location? 
Perhaps the synonyms should be narrow or related instead of exact since those terms may be more associated with the cell found in the gut.

The term in the [priority new cell types list](https://docs.google.com/spreadsheets/d/1WTs7AFd4outzbr_w-ct6Us1F4owYUKzTG0C-nzh-0jQ/edit#gid=0) has an associated reference specific to the eye (cornea) (PMID:28714595).

**Comment by emquardokus** [comment]
@bvarner-ebi my original request was to update definition  of "telocyte" and remove the "has exact synonym interstitial Cajal cell-like cell ICLC interstitial Cajal-like cell"   from original request:   "update the definition, and remove the has exact synonym to these terms since telocytes are not only located in the intestine and the "interstitial Cajal cell" is associated with intestines. interstitial Cajal cell-like cell ICLC interstitial Cajal-like cell" thanks
