### ISSUE TITLE
Add check to ensure of the branch is up to date with master

### ISSUE THREAD

**Issue by shawntanzk** [obophenotype/cell-ontology#1738]
Automated diff should check if branch is up to date with master before allowing the run

**Comment by shawntanzk** [comment]
Here's where I'm at:

make the first job have an output:
```
    outputs:
        up_to_date: '${{ steps.git_check.outputs.output }}'
```
With up_to_date being:
```
      - id: git_check
        run: |
            git branch incoming 
            output=$(git branch --contains master | grep incoming | wc -l)
            echo "name=output::$output" >> $GITHUB_OUTPUT
```
(to be continued...)

**Comment by ubyndr** [comment]
@matentzn I actually prepared a GHA for this task, but do we really need a GHA for this one anymore? As we discussed it with Shawn, since we do not trigger it all the time, we do not waste any time nor any resource on the actions.
I don't know if we already have a branch protection rule prevent any merge if the branch is not up to date. We can warn users with a simple rule;
<img width="780" alt="image" src="https://user-images.githubusercontent.com/20892222/211006964-6d7a6876-3f71-4719-97da-fb8eb1564f98.png">

And you see this message in the PR and not allowed to merge it

<img width="926" alt="image" src="https://user-images.githubusercontent.com/20892222/211007098-78f8baf2-3a69-49f6-968a-f714505a1e19.png">

**Comment by matentzn** [comment]
The merge rules and the action are separate concerns. I still believe the check is needed, because a diff run, manually invoked or automatically, on a branch that is not up to date with master, will cause a gibberish diff, which means (1) confusion for user and (2) a tree felled because of irrelevant energy consumption.
