### ISSUE TITLE
Term in CL that should probably in GO: alobate nucleus

### ISSUE THREAD

**Issue by lubianat** [obophenotype/cell-ontology#1830]
Term IRI: http://purl.obolibrary.org/obo/CL_0017509
Equivalents
[nucleus](https://ontobee.org/ontology/CL?iri=http://purl.obolibrary.org/obo/GO_0005634) and ([has characteristic](https://ontobee.org/ontology/CL?iri=http://purl.obolibrary.org/obo/RO_0000053) some [alobate](https://ontobee.org/ontology/CL?iri=http://purl.obolibrary.org/obo/PATO_0002506))

All other [nucleus](https://ontobee.org/ontology/CL?iri=http://purl.obolibrary.org/obo/GO_0005634)  types are in GO. 
Not sure how to proceed, but logging it here.

**Comment by addiehl** [comment]
GO doesn't want these phenotypic descriptions of nuclei. These were cellular phenotype terms once, with a CP prefix, but CP never because a real ontology, so in order to keep these terms around for use in describing particular cell types, they were changed to CL instead.

More discussion is available in #837 and #572.

**Comment by dosumis** [comment]
Closing as no action needed.
