### ISSUE TITLE
[Typo/Bug] Label says "arcuate nucleus of hypothalamus KNDy neuron", definition says "A 'KDNy' neuron ..."

### ISSUE THREAD

**Issue by lubianat** [obophenotype/cell-ontology#1833]
**CL term**
https://ontobee.org/ontology/CL?iri=http://purl.obolibrary.org/obo/CL_4023127 (arcuate nucleus of hypothalamus KNDy neuron)

**Description of typo, bug or error**

Label says "arcuate nucleus of hypothalamus **KNDy** neuron", definition says  "A '**KDNy**' neuron ..."

Should be changed from KDNy to KNDy, as far as I can tell. @shawntanzk can you confirm?

**Comment by bvarner-ebi** [comment]
@lubianat, thank you for spotting this.

Looking at [CL:4023127 'arcuate nucleus of hypothalamus KNDy neuron'](http://purl.obolibrary.org/obo/CL_4023127) and [CL:4023128 'rostral periventricular region of the third ventricle KDNy neuron'](http://purl.obolibrary.org/obo/CL_4023128), the dbxref PMID:30042117 does **not** contain the term "KDNy neuron".

For context, KNDy is an abbreviation for kisspeptin/neurokinin B/dynorphin (PMID:23959940).

A cursory online search revealed two instances of using "KDNy", but they both potentially appear to be typos. 

1: [Chapter-19---Function-of-folllicle-stimulating-hormone-and-_2022_Human-Gonad.pdf](https://github.com/obophenotype/cell-ontology/files/10661905/Chapter-19---Function-of-folllicle-stimulating-hormone-and-_2022_Human-Gonad.pdf)

2: https://etd.ohiolink.edu/apexprod/rws_etd/send_file/send?accession=mco1564676824418256&disposition=inline

In example one, "KDNy neuron (system)" is a hapax legomenon and "KNDy" is otherwise used throughout the text.

In example two, the paper uses "KDNy" throughout; however, in the abbreviations key and referenced citations, "KNDy" is used.

A cursory online search also reveals "KNDy" to be the common abbreviation.

Given the above, here is a proposal:

[ ] Update the text definition of CL:4023127 'arcuate nucleus of hypothalamus KNDy neuron' by replacing "KDNy" with "KNDy".

[ ] Update the label, synonym and text definition of CL:4023128 'rostral periventricular region of the third ventricle KDNy neuron' by replacing "KDNy" with "KNDy".

**Comment by shawntanzk** [comment]
Thanks @bvarner-ebi for helping with this, agree with your plan of action, but give the abbreviation + the 2 case use, could we make them exact synonyms too please :) 

btws @lubianat just a heads up, I have left the team at EBI and will not be able to contribute as much if at all
