### ISSUE TITLE
id for obsoleted term added as alt-id

### ISSUE THREAD

**Issue by tfhayamizu** [obophenotype/cell-ontology#1851]
Mouse Genome Informatics (MGI) regularly downloads the CL obo-formatted file 
Our most recent load failed due a problem with the input file.
Specifically, CL:0000381 ‘obsolete neurosecretory neuron’ has been added as alt_id for  CL:0000165 'neuroendocrine cell.'

[Term]
id: CL:0000165
name: neuroendocrine cell
**alt_id: CL:0000381**
 
[Term]
id: CL:0000381
name: obsolete neurosecretory neuron
is_obsolete: true
replaced_by: CL:0000165

note: If you look at all the other obsoleted terms in the CL file, they are not alt_ids for anything else. 

Again, this is causing a significant problem with our loading process, and it is an urgent problem for us.
We would greatly appreciate it if someone could take care of this as soon as possible.

Thanks in advance for your attention to this matter.
Terry Hayamizu
terry.hayamizu@jax.org

**Comment by bvarner-ebi** [comment]
@tfhayamizu, thank you for this notification. I'll investigate these recently merged terms.

**Comment by matentzn** [comment]
This is a known problem for all ontologies that migrated from being curated in OBO format to OWL. A more detailed discussion in the context of HPO: https://github.com/obophenotype/human-phenotype-ontology/issues/8021

A query that approximates this issue here is this one: https://api.triplydb.com/s/GxaSl9vYV

Basically because we are not using OBO format anymore, alt ids are no longer kept up to date. I advice to remove support for alt ids, delete them all from the ontology, and rely on the modern obsoletion patterns  using "term replaced by" and "owl:deprecated" instead (as you do, anyways).

**Comment by bvarner-ebi** [comment]
Thank you very much for the insight, @matentzn.

@dosumis, can you confirm the next step is to remove all instances of _has_alternative_id_ from CL? Does this action need to be discussed with any other stakeholders?

**Comment by tfhayamizu** [comment]
@bvarner-ebi 
Wondering whether any progress has been make on this issue.
Our next CL load is scheduled to run over the weekend.
All we need is for CL:0000381 to be removed as an alt-id for CL:0000165.

**Comment by bvarner-ebi** [comment]
@tfhayamizu, thank you for checking. An audit of the alternative IDs was requested for the tech team to review in #1857. Once this has been done, the changes can be made in CL. An audit and new release would not occur before this weekend, unfortunately.

@matentzn, would you kindly add #1857 to the tech board and advise if further information is needed?

**Comment by matentzn** [comment]
You don't need to wait for the audit for this particular change. It's illegal to have alt id to an obsolete term. The thing needing an audit is getting rid of all alt ids. I would quickly fix this issue here, it's one minute and completely uncontroversial.

However I doubt a bit that this is the only case where this happens, but I rust @tfhayamizu that you checked that it was.

**Comment by dosumis** [comment]
> You don't need to wait for the audit for this particular change. 
Agreed.

> The thing needing an audit is getting rid of all alt ids. I would quickly fix this issue here, it's one minute and completely uncontroversial.

Probably we're in agreement - but want to be explicit here for clarity: alt_ids indicate old OBO merges.  We shouldn't be creating any new ones, but existing ones should *all* be made into obsolete terms with a replaced by axiom.   Doing anything else is the same as destroying *Persistent* URLs.  I believe some effort was made to do this in the past for CL, but I don't trust that it was done comprehensively.  So, the action is to convert existing alt_ids to the standard OWL obsoletion pattern, removing all converted alt_id axioms.  

@bvarner-ebi  - I think you mentioned that there was a need to update documentation on this.  Could you point us to the bits that need to be changed.

There is a more general issue here:  The culture of ontologies in OBO format (and GO in particular) was to make a distinction between obsoletion - for which the community should be notified and given an opportunity to object, and merges, which could be done quickly at an editor's convenience.   This has been very important in the history of GO for rapid progress in ontology development . We need to discuss whether this distinction is still useful.

**Comment by bvarner-ebi** [comment]
> there was a need to update documentation on this. Could you point us to the bits that need to be changed.

Thanks for the feedback, @matentzn and @dosumis.

@dosumis- see https://oboacademy.github.io/obook/howto/merge-terms/, Step 23
@matentzn and @dosumis- can you confirm:
1. PR #1858 can be merged
2. the has_alternative_id annotation for 'neuroendocrine cell' should be deleted
3. a new CL release should be made
