### ISSUE TITLE
Should CL update how it uses RO:0002292 expresses?

### ISSUE THREAD

**Issue by bvarner-ebi** [obophenotype/cell-ontology#1859]
In CL, a protein (not a gene) is often used as Y in _X expresses some Y_.

No definition, domain or range is currently specified for [RO:0002292 expresses](http://purl.obolibrary.org/obo/RO_0002292). The assumption is this object property is used to describe some gene Y being expressed by some cell X, but without a definition or range, one cannot be sure.

Per @gouttegd, genes are only used with expresses in FBbt. As noted above, CL appears to use proteins (PRO terms) with expresses.

There appears to be [some debate on "gene expression" vs "protein expression"](https://www.researchgate.net/post/Gene-Expression-vs-Protein-Expression), so I'm wondering if there is consensus within OBO ontologies. 

Do the axioms involving expresses need to be updated in CL so genes are used opposed to proteins? Should [RO:0002292 expresses](http://purl.obolibrary.org/obo/RO_0002292) have a text definition, domain and/or range to clarify the intended use for ontology editors?

FYI, @cthoyt, @cmungall.

**Comment by dosumis** [comment]
This is meant to be a grouping relation.

The relevant definition is on the inverse relation ['expressed_in'](https://www.ebi.ac.uk/ols/ontologies/ro/properties?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FRO_0002206):

x expressed in y if and only if there is a gene expression process (GO:0010467) that occurs in y, and one of the following holds: (i) x is a gene, and x is transcribed into a transcript as part of the gene expression process (ii) x is a transcript, and the transcription of x is part of the gene expression process (iii) x is a mature gene product such as a protein, and x was translated or otherwise processes from a transcript that was transcribed as part of this gene expression process.

We could add a disjunctive domain here (with the same range on the inverse property):
'protein' or 'transcript' or 'gene' - although this would not be accessible to EL reasoner like ELK.  We could also mirror this def on the expresses side (at the risk of definitions getting out of sync).

I think that defining in this way is useful and pragmatic: biologists often switch between referring to genes and gene products when talking about expression and curatable gene expression data/assertions often comes with a different object types (gene, transcript or protein) depending on the source.   

Arguably this makes is a parent class to 'has_plasma_membrane_component' which is the predominant relation used to record protein markers for immune cells.  (The edge case is where the protein comes from a different cell - but I'm not aware of any use of has_plasma_membrane_component where this is the case).  

While there are counter arguments to this approach that appeal to more abstract ontology engineering principles (suspicions about the use of 'OR' to make heterogeneous classes; simplicity of the OP hierarchy), I think the pragmatic arguments win here.  The alternative is fragmentation of expression assertions, which I don't think is useful for anyone.

**Comment by bvarner-ebi** [comment]
Resolved in https://github.com/oborel/obo-relations/pull/687.
