### ISSUE TITLE
Claudius cell synonyms

### ISSUE THREAD

**Issue by GoogleCodeExporter** [obophenotype/cell-ontology#19]
```
    Primary label 'external supporting cell of vestibular epithelium' <http://purl.obolibrary.org/obo/CL_0002314> re-used as EXACT synonym for IRIs: <http://purl.obolibrary.org/obo/CL_0000634> 'Claudius cell'

```

Original issue reported on code.google.com by `cmung...@gmail.com` on 13 Feb 2013 at 12:01

**Comment by paolaroncaglia** [comment]
This hasn't been fixed yet

**Comment by bvarner-ebi** [comment]
Not quite sure what the action item is here... Can someone clarify what is needed? If no reply, I plan to close this ticket.
For reference, here are the current synonyms for 'Claudius cell':

<img width="662" alt="Screenshot 2022-08-22 at 13 25 54" src="https://user-images.githubusercontent.com/95643797/185920667-6d4eb68e-d482-438f-b3ac-eba04d06b619.png">

**Comment by addiehl** [comment]
The original comment from 2015 is still true:    
Primary label 'external supporting cell of vestibular epithelium' <http://purl.obolibrary.org/obo/CL_0002314> re-used as EXACT synonym for IRIs: <http://purl.obolibrary.org/obo/CL_0000634> 'Claudius cell'

Based on wikipedia, I recommend removing the exact synonym "external supporting cell of vestibular epithelium" from 'Claudius cell', because of the different anatomical areas involved.
https://en.wikipedia.org/wiki/Claudius_cell

Someone, someday, will hopefully update these ear cell types.
