### ISSUE TITLE
Review Specific Kidney cell type annotation mappings on Azimuth to find more detailed CL terms

### ISSUE THREAD

**Issue by dosumis** [obophenotype/cell-ontology#1972]
Make a google sheet with these mappings and share with Gesmira at Azimuth.

**Comment by emquardokus** [comment]
@dosumis I went through the Azimuth kidney annotations and mapped to CL IDs already a few months ago and gave to Gemira, Sanjay Jain (kidney expert) reviewed where the scRNAseq could NOT be mapped to a specific cell type in CL, but rather a superclass.  Should I give you this mapping here?

**Comment by dosumis** [comment]
> Should I give you this mapping here?

Yes please!

**Comment by emquardokus** [comment]
@bvarner-ebi I spent time with Austin Hartman and Gesmira Molla and also discussed via Zoom with the group plus Sanjay Jain who is both KPMP and HuBMAP on mapping differences; the Azimuth data is from his group.

**Comment by emquardokus** [comment]
Specific names do not exist for the following: (copied from slide deck discussion)
Afferent / Efferent Arteriole Endothelial
Ontology distinguishes but data does not 
There’s kidney afferent and efferent arteriole endothelial cells 
Broad option: endothelial cell of arteriole CL:1000412 (this is what I used for now) 
Intercalated Type B 
KPMP calls it: Intercalated Cell Type B 
2 options: 
connecting tubule intercalated cell type B - CL:4030021 (location specific)
Intercalated Cell Type B renal beta-intercalated cell : CL:0002201 (generic superclass)
(I included both of these for now)
Nothing for Cortical Vascular Smooth Muscle / Pericyte 
But it’s mapped to Vascular Smooth Muscle Cell/Pericyte (general) in ASCT+B mapping 
I used this for now 
Ellen noted that there is only Pericyte designation in cell ontology

**Comment by emquardokus** [comment]
@bvarner-ebi here is also direct to pipeline that Gesmira/Austin were going to update to map: https://github.com/hubmapconsortium/azimuth-annotate

**Comment by emquardokus** [comment]
@bvarner-ebi @dosumis 
Main issues are due to data not being able to distinguish between more specific cell types listed in CL --or-- cell states being indicated, which are not captured in CL; this will be a recurrent theme for all Azimuth mappings.

[mappingToAzimuth-Kidneyv1.2-copy.xlsx](https://github.com/obophenotype/cell-ontology/files/11484848/mappingToAzimuth-Kidneyv1.2-copy.xlsx)
Attached is a mapping between Azimuth that you sent to current v1.2 Kidney ASCT+B table which links directly to Cell Ontology. 

The columns are as follows: 

Azimuth Label	—this is exactly what you sent

Author's preferred name (CT/1)	this is what the KPMP group provided as preferred or typically used name

CT/1/LABEL (rdfs:label directly form cell ontology)	 this label comes DIRECTLY from cell ontology and often has disambiguating label also known as “rdfs:label"

CT/1/ID (cell ontology ID)	This is directly from cell ontology
 
CT/1/ABBR	this is a common abbreviation provided by KPMP

CT/1/NOTES these are additional notes from KPMP 

I used what was mapped between KPMP with our group to cell ontology. 

There are only a few that do not exactly match only because of the lack of specificity of cell type or more specific version of a general cell type. 

See RED entries where there is some negotiation.

=====
Afferent / Efferent Arteriole Endothelial	too vague, realize data may not distinguish, but ontology does—otherwise, we could choose 	
endothelial cell of arteriole CL:1000412

Afferent Arteriole Endothelial Cell	kidney afferent arteriole endothelial cell	CL:1001096	EC-AA
Efferent Arteriole Endothelial cell	kidney efferent arteriole endothelial cell	CL:1001099	EC-EA

----
Intercalated Type B 	Intercalated Cell Type B	connecting tubule intercalated cell type B	CL:4030021	IC-B
Intercalated Type B         Intercalated Cell Type B	renal beta-intercalated cell	CL:0002201	IC-B

=========

Our kidney v1.2 table is directly coming from Sanjay Jain and company from KPMP. 

Cycling Mononuclear Phagocyte 	BEST match due to cell state NOT being represented in Cell ontology 
mononuclear phagocyte	mononuclear phagocyte	CL:0000113

**Comment by bvarner-ebi** [comment]
Thanks very much, @emquardokus! The presentation and spreadsheet are both accessible via the links you provided.
Closing this ticket. @dosumis, please do reopen if something else is required.
