### ISSUE TITLE
[Logical def] Update bladder urothelial cell classes

### ISSUE THREAD

**Issue by bvarner-ebi** [obophenotype/cell-ontology#2015]
Updated based on [feedback below.](https://github.com/obophenotype/cell-ontology/issues/2015#issuecomment-1584326810)

**CL terms**
CL:1001428 ‘[bladder urothelial cell](http://purl.obolibrary.org/obo/CL_1001428)’
CL:1000442 '[urothelial cell of trigone of urinary bladder](http://purl.obolibrary.org/obo/CL_1000442)'

**Suggested revisions**
To support related tickets #1999 and #1975, the following are proposed edits:

**CL:1001428 ‘[bladder urothelial cell](http://purl.obolibrary.org/obo/CL_1001428)’:**
- [x] **Add text definition:**
"A urothellial cell that is part of the urothelium of the urinary bladder."
doi:10.1038/s41385-022-00565-0

- [x] **Edit SubClassOf axioms:**
**delete**: 'bladder cell'
**delete:** 'urothelial cell'
**delete**: 'part of' some 'urinary bladder urothelium'

**CL:1000442 '[urothelial cell of trigone of urinary bladder](http://purl.obolibrary.org/obo/CL_1000442)':**

- [x] **Edit logical definition:**

**current:**
```
'urothelial cell'
 and ('part of' some 'trigone of urinary bladder')
```
**proposed:**
```
'urothelial cell'
 and ('part of' some 
    (urothelium
     and ('part of' some 'trigone of urinary bladder')))
```

- [x] **Edit SubClassOf axioms:**
**delete:** 'urothelial cell'

**Comment by dosumis** [comment]
Why is this change needed?

The current logical definition provides a precise location and is sufficient for autoclassification. The proposed change does breaks both of these.

**Comment by dosumis** [comment]
Ahh - think I now undertand.  Aims is to infer classifcation of  'urothelial cell of trigone of urinary bladder’.  But isn't this part of the urothelium of the trigone?  Could be fixed by either extending Uberon to add term for this, or by anonymously referring to it in the logical def 

'urothelial cell of trigone of urinary bladder’ EquivalentTo 'urothelial cell' and part_of some (urothelium and part of some 'trigone of urinary bladder')

If you do this, then I would recommend the following fixes:


- [ ] **Add text definition:**
"A urothellial cell that is part of the urothelium of the urinary bladder."
doi:10.1038/s41385-022-00565-0


- **retain  logical definition:**
**current**: 'urothelial cell' and ('part of' some 'urinary bladder urothelium’)

- [ ] **Delete all SubClassOf axioms:**
**delete**: 'bladder cell' (will be inferred)
**delete:** 'urothelial cell' (will be inferred)
**delete**: 'part of' some 'urinary bladder urothelium' (redundant with logical def)
