### ISSUE TITLE
Clarifying the 'plural term' annotation properties

### ISSUE THREAD

**Issue by bvarner-ebi** [obophenotype/cell-ontology#2045]
CL currently has at least four versions of the annotation property concept 'plural term':

-http://purl.obolibrary.org/obo/uberon#PLURAL 
(present in the '[enteroglial cell](http://purl.obolibrary.org/obo/CL_4040002)' class)

-http://purl.obolibrary.org/obo/uberon/core#PLURAL (in merged_import)
(present in the '[retinal astrocyte](http://purl.obolibrary.org/obo/CL_4033015)' class)

-http://purl.obolibrary.org/obo/cl#PLURAL 
(present in the '[mesenchymal stem cell](http://purl.obolibrary.org/obo/CL_0000134)' class)

-http://purl.obolibrary.org/obo/caloha-reqs-vetted#PLURAL
(present in the '[colon endothelial cell](http://purl.obolibrary.org/obo/CL_1001572)' class)

- [ ] **Which is the correct annotation property to use for synonyms in native CL classes?**

**Comment by gouttegd** [comment]
I _think_ the way forward is to use OBO-wide standard annotation properties instead of letting each ontology mint its own synonym types (except in case where the synonym type is specific to the domain of the ontology).

In this instance, [OMO](https://github.com/information-artifact-ontology/ontology-metadata) now has [OMO:0003004](http://purl.obolibrary.org/obo/OMO_0003004) (“plural form”), so CL (and Uberon for that matter) should probably phase out the use of all three properties mentioned in the ticket in favour of the standard OMO one.

**Comment by bvarner-ebi** [comment]
Discussed at 07-2023 CL meeting:

Using OMO annotation property is agreeable - good as a long term solution. Notify users (via Slack channel, release notes) before changing.

- [ ] Work with @anitacaron for adding OMO import to CL and Uberon.
