### ISSUE TITLE
[Typo/Bug] IAO_0000028 as both property and class

### ISSUE THREAD

**Issue by jahilton** [obophenotype/cell-ontology#2080]
**CL term**
IAO_0000028

**Description of typo, bug or error**
Trying to load `cl.owl` from the 2023-07-20 release with owlready2 0.38 produces:
`TypeError: 'http://purl.obolibrary.org/obo/IAO_0000028' belongs to more than one entity types (cannot be both a property and a class/an individual)!`

Looks like IAO_0000028 is defined twice in the owl
once as `<owl:AnnotationProperty rdf:about="http://purl.obolibrary.org/obo/IAO_0000028"/>`
and another time as `<owl:Class rdf:about="http://purl.obolibrary.org/obo/IAO_0000028">`

**Comment by dosumis** [comment]
I believe that this officially allowed by the OWL spec

https://www.w3.org/TR/owl2-new-features/#F12:_Punning

So, strictly speaking the problems is with `owlready2 0.38`.  However, this punning is rarely used and I suspect that problems and confusion caused by it are one reason why, historically, we've never had an IAO import despite using some IAO terms.  We should not be breaking downstream pipelines just to import a tiny amount of metadata for a single term.  OMO should provide a more sustainable solution in future.

Fix for now: 

- [ ] turn off IAO import and add the rdfs:label for IAO synonym in the cl-edit file.  
- [ ] add OMO ticket requesting symbol 
- [ ] add owl2ready ticket requesting support for punning - owl2ready should support all of owl2, and we do have some use cases for Individual:Class punning so we may use it at some point in the wider family of OBO ontologies.

**Comment by anitacaron** [comment]
The next CL release will be next Thursday, 25th August.
