### ISSUE TITLE
Classifying amacrine cells as GABAergic vs Glycinergic

### ISSUE THREAD

**Issue by dosumis** [obophenotype/cell-ontology#2082]
We have an impressive diversity of amacrine neuron types in CL

<img width="919" alt="image" src="https://github.com/obophenotype/cell-ontology/assets/112839/6ab1573b-4946-4332-8d09-50535bcbedb6">

It's striking that none of the morphological types are classified under GABAergic or glycinergic.  Do we know enough about at least some of these morphological types to classify them by NT?  One potential ref https://www.frontiersin.org/articles/10.3389/neuro.02.006.2009/full

**Comment by aleixpuigb** [comment]
It's on my list to work on amacrine cells at some point. They need classification by NT and by dendrite field (narrow, medium and wide). Many amacrine cells in CL are Rabbit or Mouse specific, and their human homolog is missing. I

**Comment by aleixpuigb** [comment]
After some research I have prepared a table that represents the amacrine cells in the different species. Amacrine cells can be classified in three groups : narrow field amacrine cells (glycinergic), medium field amacrine cells (GABAergic) and wide field amacrine cells (GABAergic). The majority of amacrine cells in CL come from [an article of 1998 in rabbits](https://www.sciencedirect.com/science/article/pii/S089662730080478X?via%3Dihub). For some reason they were not classified (in the article they are, so that will be straightforward. Some name have changed in the last 25 years and will need to be revised. I can start addressing proper hierarchy, sorting by NT and dendritic field, and in separate tickets edit the existing cells and add the new ones (mainly human and non-human primates).

**Comment by aleixpuigb** [comment]
**Correction**
Per https://doi.org/10.1016/j.preteyeres.2020.100844
![image](https://github.com/obophenotype/cell-ontology/assets/94959119/1e12e531-6945-4492-91df-b54b70680e24)

Therefore, although highly correlated, NT classification has to be independent of morphology. Each cell type will be classified independently and the definition will reflect the NT(s) that they express with appropriate references.
