### ISSUE TITLE
Edit 'lung neuroendocrine cell'

### ISSUE THREAD

**Issue by ghost** [obophenotype/cell-ontology#2117]
Inspired by #2081.

After reviewing the Cell Guide "Experimental Description" for 'lung neuroendocrine cell' and finding cross-references to validate aspects of the description, the following edits are proposed:

**CL:1000223 ‘lung neuroendocrine cell’**
- [x] **add text definition:** 
"A neuroendocrine cell that is part of respiratory epithelium of the lung and is involved in the sensory detection of environmental stimuli, including hypoxia, nicotine and air pressure. Ultrastructurally, this cell type is characterized by the presence of cytoplasmic dense core granules, which are considered the storage sites of amine and peptide hormones. Lung neuroendocrine cells are innervated and appear as solitary cells or as clustered masses, localized at airway bifurcation sites, called neuroepithelial bodies that can release serotonin in response to hypoxia and interact with sensory nerve terminals. Lung neuroendocrine cells also function as reserve stem cells that repair the surrounding epithelium after injury."
PMID:33355253
doi:10.3109/01902148209069653
doi:10.7554/eLife.78216

- [x] **add SubClass of axioms:**
- 'chemoreceptor cell'
- ‘capable of’ some ‘serotonin secretion’
- 'capable of' some 'detection of hypoxia'
- 'has part' some 'dense core granule'

- [x] **add synonyms:**
- "pulmonary neuroendocrine cell", exact, PMID:33355253
- "PNEC", related, abbreviation, PMID:33355253
----
**UBERON:0010002 'pulmonary neuroendocrine body'** (Uberon ticket: https://github.com/obophenotype/uberon/issues/3035)

- [x] **edit axiom:**
CURRENT: 'has part' some 'neuroendocrine cell'
PROPOSED: 'has part' some ‘lung neuroendocrine cell'

- [x] **edit synonym:**
CURRENT: "NEB", exact
PROPOSED: "NEB", related, abbreviation

**Comment by bvarner-ebi** [comment]
> chemoreceptor cell: "A cell specialized to detect chemical substances and relay that information centrally in the nervous system." **Equivalent to**: [neuron](https://www.ebi.ac.uk/ols/ontologies/cl/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FCL_0000540) and [capable of](https://www.ebi.ac.uk/ols/ontologies/cl/properties?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FRO_0002215) some [detection of chemical stimulus involved in sensory perception](https://www.ebi.ac.uk/ols/ontologies/cl/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FGO_0050907)
> 
> Is there evidence that lung neuroendocrine cells relay chemosensory info to the nervous system / function in sensory perception? If not, the classification is not correct.

Thanks for the review.
PMID:33355253 provides evidence to align with the text definition of 'chemoreceptor cell':

<img width="652" alt="Screenshot 2023-08-22 at 13 10 16" src="https://github.com/obophenotype/cell-ontology/assets/95643797/bcefa6a0-49cb-4664-8a43-6b53f5b7d964">

The same reference states: "[pulmonary neuroendocrine cells] can detect hypoxic conditions through **chemoreception**".

CL also defines neuroendocrine cells as (possibly controversially) neurons, so that is aligned with the logical definition of 'chemoreceptor cell'.

Thank you for the GO term suggestion. 

ACTIONS:

- [ ] **Add SubClass of 'capable of' some 'detection of hypoxia'** 

- @dosumis, if you still have reservations of keeping SubClass Of 'chemoreceptor cell' after the justification above, kindly advise.

**Comment by dosumis** [comment]
The text def should include information about the interaction of these cells with sensory (and other) nerve terminals and should be explicit about their sensory role.  

(BTW: This is a good example of why standard citation practice in defs is a good thing - it would point me and anyone else directly to the relevant paper supporting specific assertions,.  Will get more important if the number of refs increases.)

(Note: The point of the EquivalentClass def of "chemoreceptor cell' is to support automated classification)

**Comment by dosumis** [comment]
Could also add:

subClassOf: has_part some 'dense core granule' http://purl.obolibrary.org/obo/GO_0031045

**Comment by bvarner-ebi** [comment]
> The text def should include information about the interaction of these cells with sensory (and other) nerve terminals and should be explicit about their sensory role.

What is your proposed revision to a necessary and sufficient text definition?

> 
> (Notes - more minor issues:
> 
> • This is a good example of why standard citation practice in defs is a good thing - it would point me and anyone else directly to the relevant paper supporting specific assertions,. Will get more important if the number of refs increases.)

This point was discussed multiple times already in CL/EBI meetings and voted against. Currently CL text definitions are not intended to be discursive descriptions and should therefore not require a high number of cross-references. Feel free to add to future CL meeting agenda for further discussion.

> * The point of the EquivalentClass def of "chemoreceptor cell' is to support automated classification, so we could achieve it by adding another capable_of link here, but might be better to request a sensory detection of hypoxia term from GO.)

ACTION:
 - [ ] remove SubClass Of 'chemoreceptor cell'
 - [ ] add SubClassOf 'has part' some 'dense core granule'

**Comment by aleixpuigb** [comment]
> remove SubClass Of 'chemoreceptor cell'

I agree with @bvarner-ebi  to maintain SubclassOf 'chemoreceptor cell', or at least add`'part of' some 'mechanosensory system'` (see https://doi.org/10.7554/eLife.78216).
![image](https://github.com/obophenotype/cell-ontology/assets/94959119/addfd180-36cc-4edd-bd46-6ba11268b5d9)

**Comment by dosumis** [comment]
> What is your proposed revision to make this a necessary and sufficient text definition?

My point is that a sensory role should be clear to anyone reading the text def. It is currently not 'detecting enrvironmental stimuli != role in sensory perception.  Mentioning connection to afferent and efferent nerve fibers makes potential sensory and effector (neuroendocrine) roles much clearer. How about:

"A neuroendocrine cell that is part of respiratory epithelium of the lung and is involved in the sensory detection of environmental stimuli, including hypoxic conditions.. Ultrastructurally, this cell type is characterized by the presence of cytoplasmic dense core secretory granules. Lung neuroendocrine cells are associated with both afferent and efferent nerve terminals.  They appear as solitary cells or as clustered masses, localized at airway bifurcation sites, called neuroepithelial bodies that can release serotonin in response to hypoxia. The lung neuroendocrine cell type is also reported to have stem cell properties."

I'm also not keen on the last sentence. general we should avoid terms like  'reported'  in defs  and 'stem cell properties' is vague. If they evidence is strong enough, it should be stated that they are capable of acting as stem cells or giving rise to stem cells? Otherwise, this is better relegated to a comment.

**Comment by bvarner-ebi** [comment]
> I'm also not keen on the last sentence. general we should avoid terms like 'reported' in defs and 'stem cell properties' is vague. If they evidence is strong enough, it should be stated that they are capable of acting as stem cells or giving rise to stem cells? Otherwise, this is better relegated to a comment.

Thank you for the suggested revision.

Agreed on last sentence. Will change to: 
"Lung neuroendocrine cells also function as reserve stem cells that repair the surrounding epithelium after injury."
doi:10.7554/eLife.78216

>"Lung neuroendocrine cells are associated with both afferent and efferent nerve terminals."

If you would like this sentence added, please provide a reference that asserts this for both solitary cells as well as those in the neuroepithelial bodies. In my review, I've only read about the efferent connections in the neuroepithelial bodies.

>My point is that a sensory role should be clear to anyone reading the text def. It is currently not 'detecting enrvironmental stimuli != role in sensory perception. Mentioning connection to afferent and efferent nerve fibers makes potential sensory and effector (neuroendocrine) roles much clearer.

Can you give an example in animals where detecting an environmental stimulus does not involve sensory perception?

**Comment by bvarner-ebi** [comment]
Thank you for the feedback, @dosumis.
Hopefully [the revised text definition](https://github.com/obophenotype/cell-ontology/issues/2117#issue-1859737467) reflects your suggestions.
