### ISSUE TITLE
Update labels to pulmonary terms

### ISSUE THREAD

**Issue by aleixpuigb** [obophenotype/cell-ontology#2169]
Some pulmonary term labels are outdated and SMEs have requested to update them. The old label will be maintained as an exact synonym:
| ID | Current label | New label |
|--|--|--|
| CL:0002062 | type I pneumocyte | pulmonary alveolar type 1 cell |
| CL:0002063 | type II pneumocyte | pulmonary alveolar type 2 cell |
| CL:4028006 | alveolar type 2 fibroblast cell | alveolar adventitial fibroblast |
| CL:4040003| fetal pre-type II pneumocyte | fetal pre-type II pulmonary alveolar epithelial cell |

Is there any other cell type that should be relabeled, @gpryhuber?

**Comment by aleixpuigb** [comment]
To do:
- pneumocyte (CL:0000322)
    - [ ] Change pneumocyte label to 'pulmonary alveolar epithelial cell'
    - [ ] Update definition with references
    - [ ] Add pneumocyte as an exact synonym with a reference
 - type I pneumocyte
    - [ ] Change 'type I pneumocyte' label to 'pulmonary alveolar type 1 cell'
    - [ ] Update definition with references
    - [ ] Add ' type I pneumocyte' as an exact synonym with a reference
- type II pneumocyte
    - [ ] Change 'type II pneumocyte' label to 'pulmonary alveolar type 2 cell'
    - [ ] Update definition with references
    - [ ] Add 'type II pneumocyte' as an exact synonym with a reference
 - 
    - [ ] Change 'alveolar type 2 fibroblast cell' label to 'adventitial fibroblast'
    - [ ] Update definition references
    - [ ] Add 'alveolar type 2 fibroblast cell' as an exact synonym with a reference

**Comment by gpryhuber** [comment]
In answer to "The following ticket was https://urldefense.com/v3/__https://github.com/obophenotype/cell-ontology/issues/2169__; I am waiting feedback from @gpryhuber on 1. since there adventitial fibroblast in non alveolar location, if it would be acceptable the label 'alveolar adventitial fibroblast' 
Reply: in reference to CL:4028006 - while I agree that there are "adventitial fibroblasts occuring in non-alveolar locations in the lung, currently we are not able to distinguish them well,  this term may change again as data resolution increases but currently the preference is CL:4028006 as adventitial fibroblast with synonyms "Alveolar Fibroblast 2 cells, matrix fibroblast 2, mesenchymal alveolar niche cell, MANC, type-2 associated stromal cell, TASC, alveolar type 2 fibroblast cell"

and 2. if there are any other cell types that should be relabeled. If the label is ok and there aren't any other terms that need to be relabeled, I will change them. Reply:  the other relabels are good to go.  We are actively working on the lung cell nomenclature project cross-consortium and other relabels may come up in next 6 months.

**Comment by gpryhuber** [comment]
Please clarify my comment on CL:4028006 - requested term "adventitial fibroblasts" - quite clearly should   not   be "alveolar adventitial fibroblasts".  The cells being described are more proximal in location and less or not at all in alveoli, this is based on [Travaglini](doi: 10.1038/s41586-020-2922-4.) and more recent unpublished data.  I do suggest that since adventitial fibroblasts are likely to occur in other tissues as well, that we use "adventitial fibroblasts of lung" or "adventitial fibroblasts, pulmonary" Synonyms listed above still hold.  Thanks

**Comment by aleixpuigb** [comment]
Thank you for your comment! I agree that adventitial fibroblast are not restricted to alveolus. However, in CL, 'alveolar type 2 fibroblast cell' is `part of alveolus`. That means that all 'alveolar type 2 fibroblast cells' are part of the alveolus. We can model this in the ontology in two ways:
1) Add an 'adventitial fibroblast' (general for all airways), and a Subclass 'alveolar adventitial fibroblast'. The second one would be the one substituting 'alveolar type 2 fibroblast cells'. 
2) Relabel 'alveolar type 2 fibroblast cells' to 'adventitial fibroblast'. Then I need to change the axiom to `part of some airway`, and add an axiom to alveolus of lung `has part adventitial cell of lung`.

Based on the current definition, I am inclined to the first option, as otherwise I am changing from a specific cell type to a broader one.
