### ISSUE TITLE
[Text def] Purkinje neuron

### ISSUE THREAD

**Issue by dosumis** [obophenotype/cell-ontology#2176]
**CL term**

CL:0000121 ; Purkinje cell

**Suggested revision of textual definition**

The current textual definition is embarrassingly bad 

![image](https://github.com/obophenotype/cell-ontology/assets/112839/456afc10-2103-47b1-9859-a8567e69461f)

Reads as if the cortex has a single type of output neuron!  More detail needed -CellGuide could be good inspiration (although probably too detailed) https://cellxgene.cziscience.com/cellguide/CL_0000121

**Comment by bvarner-ebi** [comment]
@dosumis, thank you for the issue.

While there certainly appears to be opportunity to enhance the text definition of this class, it currently appears sufficient to define ‘Purkinje cell’ of the cerebellar cortex.

(emphasis added in quoted text below)

https://www.ncbi.nlm.nih.gov/books/NBK10865/:
“The Purkinje cells project in turn to the [deep cerebellar nuclei](https://www.ncbi.nlm.nih.gov/books/n/neurosci/A2251/def-item/A2402/). **They are the only output cells of the [cerebellar cortex](https://www.ncbi.nlm.nih.gov/books/n/neurosci/A2251/def-item/A2334/)**. Since the Purkinje cells are GABAergic, the output of the cerebellar cortex is wholly inhibitory. However, the deep cerebellar nuclei receive excitatory [input](https://www.ncbi.nlm.nih.gov/books/n/neurosci/A2251/def-item/A2546/) from the collaterals of the mossy and [climbing fibers](https://www.ncbi.nlm.nih.gov/books/n/neurosci/A2251/def-item/A2362/). The [Purkinje cell](https://www.ncbi.nlm.nih.gov/books/n/neurosci/A2251/def-item/A2806/) inhibition of the deep nuclei serves to modulate the level of this excitation ([Figure 19.9](https://www.ncbi.nlm.nih.gov/books/NBK10865/figure/A1302/?report=objectonly)).”

https://doi.org/10.1038/s41593-020-00754-9:
“We also emphasize the two feedforward, excitatory inputs to **the sole output neurons of the cerebellar cortex, the Purkinje cells**…”

https://doi.org/10.1146/annurev-neuro-091421-125115:
“The cerebellar cortex contains a central trisynaptic arc: Primary input from mossy fibers (MFs) excites granule cells (GrCs), **which in turn excite Purkinje cells (PCs) that provide the sole output synapses of the cerebellar cortex** (Figure 1a).”

In addition to the CellGuide link, if you have specific primary sources to review, kindly share in this issue.

**Comment by dosumis** [comment]
I'm always a bit skeptical when I see claims like this as we may not yet have sufficiently comprehensive knowledge to definitively make such a claim given the complexity of the brain and the almost inevitable lack of comprehensive data.  I'm happy to go with the literature consensus for now and revise in future if needed.  I'd still like more detail in the definition though.  Can you have a go at finding more refs?

**Comment by AvolaAmg** [comment]
Hi there, please find an updated version of the text definition for Purkije cells. @dosumis  Let me know if you are okay with this definition and I can turn it into a PR:

**Updated definition of Purkinje cell**:

An inhibitory neuron and the sole output neuron of the cerebellar cortex, the Purkinje cell's soma is located between the granular and molecular layers of the cerebellum. It is one of the largest neural cells in the mammalian brain, ranging from 50 to 80 micrometers in diameter.

A Purkinje cell presents planar, fan-shaped dendrites that branch extensively with little overlap. This cell receives synaptic input from parallel fibers, which modulate high-frequency spike activity known as "simple spikes," and climbing fibers, which modulate infrequent calcium spike activity known as "complex spikes."

Purkinje cells are involved in motor coordination, particularly in correcting movements in progress.

**database_cross_reference:**
[PMID:31424738](https://pubmed.ncbi.nlm.nih.gov/31424738/#:~:text=Purkinje%20cells%20are%20a%20unique,learn%20by%20remodeling%20their%20dendrites.)
[PMID:12907269](https://pubmed.ncbi.nlm.nih.gov/12907269/)
[PMID:38168772](https://pubmed.ncbi.nlm.nih.gov/38168772/)
[PMID:14568361](https://pubmed.ncbi.nlm.nih.gov/14568361/)
[PMID:33288911](https://pubmed.ncbi.nlm.nih.gov/33288911/)

**has_an_exact_synonym:**
PC
**synonym_type:**
abbreviation
**database_cross_reference:**
[PMID:38168772](https://pubmed.ncbi.nlm.nih.gov/38168772/)

updated references for all the other synonyms:
cerebellar Purkinje cell
https://doi.org/10.1016/j.proghi.2004.07.002

Purkinje neuron
PMID: [28821816](https://pubmed.ncbi.nlm.nih.gov/28821816)

**has_exact_synonym:**
PN
PMID: [28821816](https://pubmed.ncbi.nlm.nih.gov/28821816)
**synonym type:**
abbreviation


**Comments:**
Neurodegenerative disorders affecting Purkinje cells disrupt motor functions. Some of the neurodegenerative disorders that causes loss and degeration of Purkinje cells are Spinocerebellar ataxias (SCAs) [Josef P Kapfhammer and Etsuko Shimobayashi], Friedreich's ataxia (FRDA) [Kevin C Kemp et al., 2016], Fetal alcohol syndrome [Laurent Servais et al., 2016], Dandy-Walker malformation [Alexander Atamian et al., 2024].

**references**
[PMID:37426070](https://pubmed.ncbi.nlm.nih.gov/37426070)
[PMID:27215193](https://pubmed.ncbi.nlm.nih.gov/27215193)
[PMID:17535929](https://pubmed.ncbi.nlm.nih.gov/17535929)
[https://doi.org/10.1016/j.stem.2023.11.013](https://doi.org/10.1016/j.stem.2023.11.013)

**Comment by dosumis** [comment]
Looks good to me.  

Might consider whether to use any content/refs from https://cellxgene.cziscience.com/cellguide/CL_0000121

I think there is sufficient content here to replace the CellGuide def.  We need a mechanism to flag defs where this is the case.

**Comment by AvolaAmg** [comment]
Thanks for your comment! I think for neuronal related term we could start an epic that goes hand in hand with the one that mean to clean the hierarchy under neuron.
I Will start a PR on this then.
