### ISSUE TITLE
Add subset tag for CellxGene usage

### ISSUE THREAD

**Issue by dosumis** [obophenotype/cell-ontology#2252]
Investigate whether we can mine CxG Census to find all CL terms in use on CxG.  If yes, build GA pipeline to mine CxG for a CL term list + ROBOT pipeline to tage CL terms with subset tag: cellxgene_subset. (If not possible - request functionality from CxG Census?)

@anitacaron - this is very similar to what we already do for HRA.  Can you point @hkir-dev  to existing pipelines?

**Comment by anitacaron** [comment]
The pipeline for HRA is in the `ccf-validation-tools`. It might be better to use the subset pipeline from ODK, the same as the other subsets here, e.g. eye, kidney, etc.

**Comment by anitacaron** [comment]
Or generate a component from the ROBOT template.

**Comment by hkir-dev** [comment]
I prepared an experimental project https://github.com/hkir-dev/cellxgene-cell-reporter

A nightly build GitHub action is generating 
- A robot template: https://github.com/hkir-dev/cellxgene-cell-reporter/blob/main/templates/cellxgene_subset.tsv
- An ontology: https://github.com/hkir-dev/cellxgene-cell-reporter/blob/main/cellxgene_subset.owl

@anitacaron how can we integrate this to CL?

**Comment by anitacaron** [comment]
- [ ] 1. Update the `cl-odk.yaml` following this example: https://github.com/obophenotype/cell-ontology/blob/bf0391d3a173c552873beab5d202fb5daa95f4c1/src/ontology/cl-odk.yaml#L113-L116

The template file should be in `src/templates`. ODK will generate the owl file in the `src/ontology/components`, no need to add it.
- [ ] 2. Inside `src/ontology`, run `sh run.sh make update_repo`

- [ ] 3. Add the component URL to the catalog: example https://github.com/obophenotype/cell-ontology/blob/bf0391d3a173c552873beab5d202fb5daa95f4c1/src/ontology/catalog-v001.xml#L21
- [ ] 4. Add the component URL as an import in the cl-edit (in alphabetical order): example ```Import(<http://purl.obolibrary.org/obo/cl/components/kidney_upper_slim.owl>)```
- [ ] 5. Add a rule to update the template in `cl.Makefile`: the example is downloading a component because there isn't a template, but in your case, you should download the template. (In the next ODK version, this step won't be necessary; we'll be able to just pass the link to an external template in the cl-odk.yaml file)
https://github.com/obophenotype/cell-ontology/blob/bf0391d3a173c552873beab5d202fb5daa95f4c1/src/ontology/cl.Makefile#L230-L235
- [ ] 6. Inside `src/ontology`, run `sh run.sh make components/{owl file name}` to generate the owl file

Let me know if you need further help.
