### ISSUE TITLE
NTR for cell states from Azimuth and DOSDP to add them

### ISSUE THREAD

**Issue by aleixpuigb** [obophenotype/cell-ontology#2354]
An increasing number of single cell transcriptomics are identifying cell states that are transcriptionally unique. CL editors have decided on the call of November 2023 that these cell states can be added in CL:
![image](https://github.com/obophenotype/cell-ontology/assets/94959119/30e886aa-cb9e-4e5e-9f18-e75af4b478b3)

The cell types can be added using a dessign pattern. I have compiled a [list of terms from Azimuth](https://docs.google.com/spreadsheets/d/1kmw-9wKF7kjdNcfzZGeFRWjvo35bY7rKuEKNXc7i9A4/edit#gid=0) that can be added.
Need:
- Parent cell term
- GO term (object property 'is capable of')
- Create automatic definition: Any "parent term" that is capable of "GO term".
- References

@emquardokus, feel free to add more cell states in the spreadsheet.

**Comment by dosumis** [comment]
I would like to just add 'cycling' terms for now.

> GO term (object property 'is capable of')

We will need a new OP.  We need to be able to record that the cell is participating in the process not that id could do.

**Comment by dosumis** [comment]
Decision: We will go with {cell} and participates_in some M-phase as a DOSDP.

**Comment by rays22** [comment]
I am looking at the ['Cell states'](https://docs.google.com/spreadsheets/d/1kmw-9wKF7kjdNcfzZGeFRWjvo35bY7rKuEKNXc7i9A4/edit?gid=0#gid=0) table that is referenced [above](https://github.com/obophenotype/cell-ontology/issues/2354#issue-2260872714) to get a better idea of what "cycling" is intended to mean in this context.

1. All the "cycling" cell types are immune cells.
2. The table quotes [GO:0051301 cell division](https://www.ebi.ac.uk/ols4/ontologies/go/classes/http%253A%252F%252Fpurl.obolibrary.org%252Fobo%252FGO_0051301) in relation to cycling, but I have serious doubts that this term would be the right choice for the logical definition of a "cycling" cell state.

I have sat through countless immunology seminars going back decades, and historically and typically it was flow cytometry (FACS) that provided the evidence for the cycling or dividing state of immune cells. Flow cytometry is an excellent tool to detect what GO defines as [cell cycle phases](https://www.ebi.ac.uk/ols4/ontologies/go/classes/http%253A%252F%252Fpurl.obolibrary.org%252Fobo%252FGO_0022403?lang=en). When they detect significant proportions of S-phase and M-phase states in the population, then they usually say that these are cycling cells.
Individual cells may be in an S-phase or M-phase or any other "cycling" state. Most (all?) immune cells are capable of going through all the phases of the cell cycle, and I think "cycling" is intended to mean that these cells are actively participating in the process.

For the reasons above, a GO cell cycle process term would be probably more appropriate than [GO:0051301 cell division](https://www.ebi.ac.uk/ols4/ontologies/go/classes/http%253A%252F%252Fpurl.obolibrary.org%252Fobo%252FGO_0051301) for the logical axioms, although I see the connection between cell cycle and cell division.
However [GO:0000279 M phase](https://www.ebi.ac.uk/ols4/ontologies/go/classes/http%253A%252F%252Fpurl.obolibrary.org%252Fobo%252FGO_0000279) would be too narrow to define a generic "cycling" state, because many cycling, proliferating or dividing cells are in a phase other than "M".
GO advise against using the grouping term [GO:0022403 cell cycle phase](https://www.ebi.ac.uk/ols4/ontologies/go/classes/http%253A%252F%252Fpurl.obolibrary.org%252Fobo%252FGO_0022403?lang=en) for direct annotation, but individual cycling cells can be in any phase of the cell cycle.
A "G2/M" state is also frequently used in papers, but GO has only separate G2 and M phase terms, and it has no "G2/M" or any other transition state terms.  

[GO:0022403 cell cycle phase](https://www.ebi.ac.uk/ols4/ontologies/go/classes/http%253A%252F%252Fpurl.obolibrary.org%252Fobo%252FGO_0022403?lang=en) could group together all cycling cell states, but more granular individual states (G1, S, G2, M) would require separate patterns, or a pattern with a slot for a variable to specify which subclass of [GO:0022403 cell cycle phase](https://www.ebi.ac.uk/ols4/ontologies/go/classes/http%253A%252F%252Fpurl.obolibrary.org%252Fobo%252FGO_0022403?lang=en) to use.

**Comment by aleixpuigb** [comment]
Thank you, @rays22 

> A "G2/M" state is also frequently used in papers, but GO has only separate G2 and M phase terms, and it has no "G2/M" or any other transition state terms.

Go has a term for this transition [cell cycle G2/M phase transition](http://purl.obolibrary.org/obo/GO_0044839). But wouldn't it be too narrow again?

**Comment by dosumis** [comment]
Hi Ray, 

All good points.

Our main motivating use case at present for single cell transcriptomics, where cycling cells cluster independently - presumably due a large and consistent shift in some part of the transcriptomic signature due to expression of genes involved in (some phase of?) the cell cycle.   Presumably the biologists involved can tell us if that transcriptomic signature indicates a particular phase of the cell cycle.

I suspect that this is not the same as cells sorted as cycling in flow cytometry.  

@rays22  - I share your concern about general usage. A term called B-cell cycling may well end up being used more generally e.g. to refer to cells typed as cycling by FACS sorting.   Maybe we will need a more concise term for the scRNAseq use case.

**Comment by rays22** [comment]
> Thank you, @rays22
> 
> > A "G2/M" state is also frequently used in papers, but GO has only separate G2 and M phase terms, and it has no "G2/M" or any other transition state terms.
> 
> Go has a term for this transition [cell cycle G2/M phase transition](http://purl.obolibrary.org/obo/GO_0044839). But wouldn't it be too narrow again?

Thanks @aleixpuigb for pointing that out. OK, then there are no gaps in GO terms related to the phases of the cell cycle process which accurately correspond to the states of individual "cycling" cells in single-cell expression experiments. I absolutely agree that  [GO:0044839 cell cycle G2/M phase transition](https://www.ebi.ac.uk/ols4/ontologies/go/classes/http%253A%252F%252Fpurl.obolibrary.org%252Fobo%252FGO_0044839) would be too narrow to describe cycling cells.

**Comment by rays22** [comment]
> I suspect that this is not the same as cells sorted as cycling in flow cytometry.

Thanks @emquardokus  [for bringing it to my attention to this paper](https://github.com/obophenotype/cell-ontology/pull/2419#discussion_r1670616352). I am looking at the paper [Riba, A., Oravecz, A., Durik, M. et al. Cell cycle gene regulation dynamics revealed by RNA velocity and deep-learning. Nat Commun 13, 2865 (2022)](https://doi.org/10.1038/s41467-022-30545-8) that show scRNA data from *cell populations* where the transcriptional states of *individual* cells are being clustered in ways to see if *cell cycle phases* can be detected.
Flow cytometry appears to be the tool in the paper to detect cell cycle phases to which correlate the RNA transcription profiles of individual cells. 

* Fig. 5C says:

> Flow cytometry analysis recapitulates fractions of cells in the main phases of the cell cycle similar to the phases identified with DeepCycle

I find no evidence for any revision of what [GO:0007049 cell cycle](https://www.ebi.ac.uk/ols4/ontologies/go/classes/http%253A%252F%252Fpurl.obolibrary.org%252Fobo%252FGO_0007049) means in case of scRNA studies compared with non-scRNA study findings:

>The subset of genes in the GOterm:cell_cycle (GO:0007049) passing through the hotelling filter (see section ‘Identification of cycling genes and high-density paths’) has been fed to the autoencoder...

> To train DeepCycle, we used the expression of unspliced and spliced RNAs of the genes in the GOterm:cell_cycle (n = 532, see ‘Implementation of DeepCycle’ in Methods

Regardless of whether scRNA clusters correlate or not with flow cytometry cell cycle phases, or any other subdivision of the "cycling" process, my point is that a "cycling" somatic cell library represents *many different states*, all of which are part of some mitotic cell cycle process, so we can *not use a GO term that is too narrow.*

**Comment by rays22** [comment]
> Thank you, @rays22
> 
> > A "G2/M" state is also frequently used in papers, but GO has only separate G2 and M phase terms, and it has no "G2/M" or any other transition state terms.
> 
> Go has a term for this transition [cell cycle G2/M phase transition](http://purl.obolibrary.org/obo/GO_0044839). But wouldn't it be too narrow again?

I think "cycling" cell in the context of this ticket (scRNA clustering data) means that significant subsets of a cell population are in the following (or similar, like [GO:0044839 cell cycle G2/M phase transition](https://www.ebi.ac.uk/ols4/ontologies/go/classes/http%253A%252F%252Fpurl.obolibrary.org%252Fobo%252FGO_0044839?lang=en)) phases/states:

* [GO:0045023 G0 to G1 transition](https://www.ebi.ac.uk/ols4/ontologies/go/classes/http%253A%252F%252Fpurl.obolibrary.org%252Fobo%252FGO_0045023)
* [GO:0000082 G1/S transition of mitotic cell cycle](https://www.ebi.ac.uk/ols4/ontologies/go/classes/http%253A%252F%252Fpurl.obolibrary.org%252Fobo%252FGO_0000082?lang=en)
* [GO:0000084 mitotic S phase](https://www.ebi.ac.uk/ols4/ontologies/go/classes/http%253A%252F%252Fpurl.obolibrary.org%252Fobo%252FGO_0000084?lang=en)
* [GO:0000086 G2/M transition of mitotic cell cycle](https://www.ebi.ac.uk/ols4/ontologies/go/classes/http%253A%252F%252Fpurl.obolibrary.org%252Fobo%252FGO_0000086?lang=en)

Individual cells, or cell groups (dots in clusters and clusters, respectively) in a typical scRNA experiment could be classified to belong any of these state/phase/process categories, or even other ("non-cycling", i.e. [GO:0044838 cell quiescence](https://www.ebi.ac.uk/ols4/ontologies/go/classes/http%253A%252F%252Fpurl.obolibrary.org%252Fobo%252FGO_0044838)) states.

**Comment by rays22** [comment]
### Proposal to define quiescent vs. cycling cell states logically based on process attributes:
* The following two attribute classes could be made also subclasses of [PATO:0001236 process quality](https://www.ebi.ac.uk/ols4/ontologies/pato/classes/http%253A%252F%252Fpurl.obolibrary.org%252Fobo%252FPATO_0001236) in PATO, or need similar new PATO process qualities.
    * [PATO:0002355 inactive](https://www.ebi.ac.uk/ols4/ontologies/pato/classes/http%253A%252F%252Fpurl.obolibrary.org%252Fobo%252FPATO_0002355?lang=en)
    * [PATO:0002354 active](https://www.ebi.ac.uk/ols4/ontologies/pato/classes/http%253A%252F%252Fpurl.obolibrary.org%252Fobo%252FPATO_0002354?lang=en)
* Other components:
    * [GO:0022402 cell cycle process](https://www.ebi.ac.uk/ols4/ontologies/go/classes/http%253A%252F%252Fpurl.obolibrary.org%252Fobo%252FGO_0022402?lang=en)
    * [RO:0000086 has quality](https://www.ebi.ac.uk/ols4/ontologies/ro/properties/http%253A%252F%252Fpurl.obolibrary.org%252Fobo%252FRO_0000086)


* "cycling" cell:
```
cell
    and ('participates in' some 'cell cycle process')
    and ('has quality' some 'active')
```

If needed, 'cell cycle process' can be substituted with more specific process/phase terms to achieve more fine grained classification.

* "quiescent" cell:
```
cell
    and ('participates in' some 'cell cycle process')
    and ('has quality' some 'inactive')
```
