### ISSUE TITLE
[NTR] spiny VIP neuron

### ISSUE THREAD

**Issue by AvolaAmg** [obophenotype/cell-ontology#2355]
Please check that the term does not already exist by using the ontology search tool OLS:
https://www.ebi.ac.uk/ols4/ontologies/cl

**cell label:**
spiny VIP neuron

**Text definition:**
A vip GABAergic cortical interneuron with a soma located in L1-3 of the neocortex in Mmus. This neuron has a multipolar morphology with spiny dendrites concentrating on L1 of the cortex and has a burst firing electrophysiological signature with highly dynamic dendritic spines.

**Database_cross_reference:**
[PMID:35418660](https://pubmed.ncbi.nlm.nih.gov/35418660/)

**Has a related synonym:**
superficial VIP-positive spiny neuron
**Database_cross_reference:**
[PMID:35418660](https://pubmed.ncbi.nlm.nih.gov/35418660/)

**Has a related synonym:**
multipolar VIP neuron
**Database_cross_reference:**
[PMID:35418660](https://pubmed.ncbi.nlm.nih.gov/35418660/)

**anatomical structure:**
[neocortex](http://purl.obolibrary.org/obo/UBERON_0001950)

**parent term:**
[vip GABAergic cortical interneuron](http://purl.obolibrary.org/obo/CL_4023016)

@aleixpuigb 
A new term to review.

**Comment by AvolaAmg** [comment]
@JABelfiore @Caroline-99 @aleixpuigb to review

**Comment by aleixpuigb** [comment]
Thank you for the term request, @AvolaAmg 

>Has a related synonym:
superficial VIP-positive spiny neuron

I think it can be an exact synonym, since superficial is referring to location L1 and L2/3:
![image](https://github.com/obophenotype/cell-ontology/assets/94959119/239c342b-85be-4100-9bbc-0a87b9583e27)

>Text definition:
A vip GABAergic cortical interneuron with a soma located in L1-3 of the neocortex in Mmus. This neuron has a multipolar morphology with spiny dendrites concentrating on L1 of the cortex and has a burst firing electrophysiological signature with highly dynamic dendritic spines.

Definition looks good. What is the nomenclature for VIP? I see it often capitalized, but the CL term [vip GABAergic cortical interneuron](http://purl.obolibrary.org/obo/CL_4023016) is not. Should it be amended? If not, this term might also have to be spiny vip neuron, but I prefer the first option and capitalize in the definition.

**Comment by AvolaAmg** [comment]
Hi @aleixpuigb thanks for your review. The paper I cite as a reference uses the capitalised version. I would prefer it capitalised as well if that is okay as VIP stands for vasoactive intestinal peptide and so it is an acronym. 
Apart from that I will turn this ticket into a PR.

**Comment by aleixpuigb** [comment]
Great, then you can relabel [vip GABAergic cortical interneuron](http://purl.obolibrary.org/obo/CL_4023016) to VIP GABAergic cortical interneuron in this ticket.

**Comment by aleixpuigb** [comment]
These are the terms that has vip in lower case in label, symbol, definition or synonym:
![image](https://github.com/obophenotype/cell-ontology/assets/94959119/69e30ed1-f078-47f1-af10-0e5bbb225e84)

**Comment by AvolaAmg** [comment]
happy to capitalise all of them
