### ISSUE TITLE
[Logical def] PR_000050567 used in logical definitions has been obsoleted

### ISSUE THREAD

**Issue by LCCarmody** [obophenotype/cell-ontology#2366]
**CL term**
Several

**Suggested revision of logical definition**
Several CL terms use PR_000050567 in logical definitions. Unfortunately, PR has obsoleted the term.

Their note is "OBSOLETE. A material entity that minimally consists of a protein. Note: Made obsolete since the term definition was much broader than intended. Originally meant to include only single proteins (and derivatives thereof; PR:000000001), protein-containing complexes (GO:0032991), and protein aggregates (PR:000050566), it instead also included cells defined as having certain protein attachments."

Please change the term.

**Comment by dosumis** [comment]
1. It's actually a good thing this has been obsoleted as it was causing almost everything in our KG to be classified as a protein containing entity - which I guess is trivially true...
2. I just checked and don't see it being used in any CL logical definitions (EquivalentClass).  However - asserted classifications under it are coming in from the Uberon import, which now appears to be pre-reasoned (I guess this is due to the move to base-plus  - even if we don't call it that).  => 207 Uberon anatomical structures classified. 
3. Running the reasoner => some quite spectacular results with lots of CL classified under it:
<img width="426" alt="image" src="https://github.com/obophenotype/cell-ontology/assets/112839/74b92d9d-528e-4ec5-9000-e99086edb52d">

I believe the we should be able to fix all of this by updating PRO in Uberon and CL (the one big import file strategy should avoid Zombie axioms)

**Comment by LCCarmody** [comment]
So I noticed this in MAXO. We do import PR (and tons from UBERON). I was just going by the usage I could seen in MAXO here. 

Thanks for looking into it. 
![Screenshot 2024-05-07 at 11 49 38 AM](https://github.com/obophenotype/cell-ontology/assets/26067008/6bbc4e08-943d-41a9-ba94-c0bfc93f71bf)

**Comment by dosumis** [comment]
You will need to update your PRO import too, if you haven't done already. The difficulty here is that, AFAIK, you will still have some residual issues if any other ontologies you import also import PRO but don't update. In these cases you will see classification of terms in the import under this term, but it shouldn't affect your terms as only the direct PRO import will pull in the PRO logical def which causes all these problems.  It's a downside of the the ODK base-plus strategy (CC @matentzn @cmungall)
