### ISSUE TITLE
gogoeditdiff failing due to FlyBase autodef dependency fail (?) 

### ISSUE THREAD

**Issue by dosumis** [obophenotype/cell-ontology#2367]
<img width="980" alt="image" src="https://github.com/obophenotype/cell-ontology/assets/112839/3e8d5e3a-82f5-4a78-9c69-8d521a9005cf">

https://github.com/obophenotype/cell-ontology/actions/runs/8988121798/job/24688289003

**Comment by gouttegd** [comment]
Almost certainly due to the fact that the `diff.yml` workflow is still using the ODK version 1.3.0 (which doesn’t include the code to install plugins), for some reason (most likely, it’s just that nobody thought of updating the version number).

I’ll do some tests. If I confirm the cause, I’ll have a fix quickly.
