### ISSUE TITLE
CL:4042013 missing in graph

### ISSUE THREAD

**Issue by iimpulse** [obophenotype/cell-ontology#2692]
CL:4042013

Lamp5 Lhx6 neuron (CL:4042013) | subClassOf (rdfs:subClassOf) | lamp5 GABAergic cortical interneuron (CL:4023011)

Hello Cell Ontology Team!

We have a general ontology parser that loads ontologies in memory. The program is attempting to build parents/children and is failing on term CL:4042013. Upon another inspecting of the cl-base.json file there is no connection with this term in the graph. Can you please ensure that the above sub class prop exists?

**Comment by gouttegd** [comment]
I believe this is because the OboGraphs library (which is responsible for the conversion to JSON) [does not handle the case](https://github.com/geneontology/obographs/blob/6676b10a5cce04707d75b9dd46fa08de70322b0b/obographs-owlapi/src/main/java/org/geneontology/obographs/owlapi/FromOwl.java#L145) where the superclass of a _SubClassOf_ axiom is a _ObjectIntersectionOf_ class expression, which is exactly how CL:4042013 is defined: it has a single _SubClassOf_ axiom with an object intersection of all the parents:

```
CL:4042013 SubClassOf: 'lamp5 GABAergic cortical interneuron'
                        and ('has soma location' some 'cerebral cortex')
                        and ('develops from' some 'caudal ganglionic eminence')
                        and ('capable of' some 'gamma-aminobutyric acid secretion, neurotransmission')
                        and (expresses some 'lysosome-associated membrane glycoprotein 5')
                        and (expresses some 'LIM/homeobox protein Lhx6 ')
```

As a result, none of those relationships appear in the JSON graph.

**Comment by gouttegd** [comment]
Ideally the OboGraphs library should be updated to handle that case, but in the meantime in CL we can (should) replace the axiom above with separate SubClassOf axioms for each member of the `ObjectIntersectionOf` expression (for CL:4042013 and any other class that use similar axioms -- there seem to be a few of them).

**Comment by dosumis** [comment]
@gouttegd  - many thanks for working out the issue. 
@iimpulse  - you should find these relationships in the other .json release files:

cl-full.json (CL + imported classes from other ontologies)
cl-simple.json (only has CL classes)

The -base files are built for use in imports rather than general public consumption.

**Comment by dosumis** [comment]
@iimpulse  - my previous comment was incorrect. I thought the problem was the treatment of EquivalentClass axioms by our release pipelines when it is actually the treatment of SubClassOf axioms with conjunctions. @gouttegd PR fixes your issue and should be reflected in the next release.

As an aside - if we classify purely by markers then LAMP5 LHX6 GABAergic cortical interneurons are a subclass of LAMP5 GABAergic cortical interneurons.  But these names are used to refer to transcriptomically distinct, non-overlapping classes:

<img width="762" alt="image" src="https://github.com/user-attachments/assets/2a105cec-e79b-4af0-98f6-052a3931e7a9">  https://cellxgene.cziscience.com/e/e4ddac12-f48f-4455-8e8d-c2a48a683437.cxg/
CC @AvolaAmg
