### ISSUE TITLE
[Typo/Bug]CL:0000163 CL:0000164

### ISSUE THREAD

**Issue by jingangdidi** [obophenotype/cell-ontology#2856]
**CL term**
CL:0000163 and CL:0000164

**Description of typo, bug or error**

Why CL:0000163 is_a is CL:0000164, and vice versa?

id: CL:0000163
is_a: CL:0000164 {gci_relation="part_of", gci_filler="UBERON:0000945"} ! enteroendocrine cell
is_a: CL:0000164 {gci_filler="UBERON:0000160", gci_relation="part_of"} ! enteroendocrine cell
is_a: CL:0000164 {gci_filler="UBERON:0001264", gci_relation="part_of"} ! enteroendocrine cell

id: CL:0000164
is_a: CL:0000163 ! endocrine cell

**Comment by dosumis** [comment]
Hi @jingangdidi

This is confusion caused by the way an OWL construct ([GCI](https://ontogenesis.knowledgeblog.org/1288/)) is expressed in OBO.

Here's what this looks like in OWL

'endocrine cell' and ('part of' some intestine) SubClassOf 'enteroendocrine cell'
'endocrine cell' and ('part of' some stomach) SubClassOf 'enteroendocrine cell'
'endocrine cell' and ('part of' some pancreas) SubClassOf 'enteroendocrine cell'

In English: Any endocrine cell that is part of the intestine is an enterendocrine cell

Is there any reason for you to use OBO?  I would recommend our JSON serialisation instead:
http://purl.obolibrary.org/obo/cl/cl.json . With this you can use the `edges` array to find relationships without encountering confusing issues like this.

@cmungall; @gouttegd  could we remove GCIs from our OBO products?  This issue comes up v.regularly.

**Comment by jingangdidi** [comment]
> Is there any reason for you to use OBO? I would recommend our JSON serialisation instead:
> http://purl.obolibrary.org/obo/cl/cl.json . With this you can use the `edges` array to find relationships without encountering confusing issues like this.

Thank you for your clarification. I encountered the use of cl.obo in [popv](https://github.com/YosefLab/PopV), I want to retrieve all parent and child types for any given id, so I write code to read cl.obo, match **id:**, **name:** and **is_a:**, then build relationships. Is it more convenient to utilize cl.json for this requirement compared to cl.obo? I understand the meaning of is_a in cl.obo is "a subclassing relationship between one term and another", making its use more intuitive. Could you elucidate what sub, pred, and obj represent within the edges, or provide some information regarding the format of cl.json?

**Comment by gouttegd** [comment]
> Is it more convenient to utilize cl.json for this requirement compared to cl.obo?

I’d say yes, because the OBO format has quite a few quirks, and parsing it is more complicated than it looks like. The use of the “qualifier” syntax to encode GCIs is a good example of the not-always-apparent complexity of the format.

The `cl.json` file follows the OBOGraphs schema, which is defined [here](https://github.com/geneontology/obographs). Basically, if you want the parent-child relationships, they are represented in the `edges` array as:

```json
{
  "sub": "<ID of the subclass>",
  "pred": "is_a",
  "obj": "<ID of the superclass>"
}
```

For example, `'enteroendocrine cell' is_a 'endocrine cell'` is represented as:

```json
{
  "sub": "http://purl.obolibrary.org/obo/CL_0000164",
  "pred": "is_a",
  "obj": "http://purl.obolibrary.org/obo/CL_0000163"
}
```

**Comment by gouttegd** [comment]
(You may also want to have a look at the [Ontology Access Kit](https://github.com/INCATools/ontology-access-kit), which aims to provide access to this kind of data without having to bother about formats and parsing.)

**Comment by canergen** [comment]
Thanks for raising this issue @jingangdidi. Code in popV is fully rewritten to use json. I still have to merge it but for this all reference models need to be retrained. @gouttegd It would be helpful to list the json as product in https://obofoundry.org/ontology/cl.html.

**Comment by gouttegd** [comment]
I assume we can close here. The original poster got their answers, the confusing GCI axioms will no longer be included in OBO products, and CL’s page on the OBO Foundry will be updated to explicitly mention the JSON products (https://github.com/OBOFoundry/OBOFoundry.github.io/pull/2665).

Feel free to re-open if an unanswered question has been missed.
