### ISSUE TITLE
CL:0000695 - cajal rtezius cell - add relationships

### ISSUE THREAD

**Issue by cmungall** [obophenotype/cell-ontology#345]
current:

[Term]
id: CL:0000695
name: Cajal-Retzius cell
namespace: cell
def: "One of a transient population of pioneering neurons in the cerebral cortex. These cells are slender bipolar cells of the developing marginal zone. One feature of these cells in mammals is that they express the Reelin gene." [PMID:10600995, PMID:9728912]
is_a: CL:0000117 ! CNS neuron (sensu Vertebrata)

\* Should this be a subtype of CL:0000116 ~ pioneer neuron?
* Also a subtype of bipolar neuron
* Also link to more specific anatomical location

Original comment by: cmungall

**Comment by shawntanzk** [comment]
> * Should this be a subtype of CL:0000116 ~ pioneer neuron?

Def needs fixing instead - seems from the above, and some reading, that pioneer neurons are different from cajal-retzius neurons and are differentiated by expression of reelin 

> Also a subtype of bipolar neuron

instead, we can use has_characteristic some bipolar morphology (since it is added to PATO now) - this should also automatically reason it into bipolar neuron

> Also link to more specific anatomical location

can add has_soma_location some UBERON:0010403 (brain marginal zone)
