### ISSUE TITLE
NTR: splenic B cell

### ISSUE THREAD

**Issue by jahilton** [obophenotype/cell-ontology#421]
label: splenic B cell
synonyms: spleen B cell
definition: A cell of the B cell lineage with the phenotype CD43-negative and CD11b-negative.
part_of: UBERON_0002106 (spleen)
is_a: CL_0000236 (B cell)
reference: http://genome.cse.ucsc.edu/ENCODE/protocols/cell/mouse/bCellCd43_Stam_protocol.pdf

**Comment by bvarner-ebi** [comment]
@addiehl, checking in on this ticket. I see it is from 2016, is unassigned, and there is a comment asking for your feedback.

**Comment by addiehl** [comment]
Looking in the literature, I don't see direct support for 'spleen B cell' with this marker combination. Splenic B-cell progenitor populations in the mouse are CD43-negative, but differentiated B-1 B cells in the spleen are CD43-positive and CD11b-positive ([PMID:21282663](https://pubmed.ncbi.nlm.nih.gov/21282663/)).

We already have 'marginal zone B cell of spleen' (CL:0000845), which would not be a subclass of this proposed cell type because the markers don't line up, even though logically any B cell subclass found in the spleen should be a subclass of a general 'spleen B cell'.

I will close this for now, and if the original requester comes back with better information, we can reconsider.  We need a better representation of human B cell subclasses found in the spleen, and hopefully these will come from HuBMAP or future literature review.
