### ISSUE TITLE
NTR: neurosphere

### ISSUE THREAD

**Issue by jahilton** [obophenotype/cell-ontology#423]
label: neurosphere
definition: A cluster of cells derived from neural stem cells in a medium lacking adherent substrates.
derived_from: CL:0000047 (neural stem cell)
reference: http://www.nature.com/protocolexchange/protocols/77

**Comment by addiehl** [comment]
This term and its suggested children are out of scope for the CL.  A cluster of cells is not a cell type, but rather an anatomical structure.  However, I'm guessing since this is not a naturally occurring anatomical structure, it's out of scope for Uberon as well.  You might be able to get it added to the Ontology for Biomedical Investigations or a related ontology.

Closed.
