### ISSUE TITLE
Fix is_a edge between CL:0000457 and CL:0000163

### ISSUE THREAD

**Issue by mbernste** [obophenotype/cell-ontology#439]
I am not a biologist, but as I understand, a 'biogenic amine secreting cell' is not always an 'endocrine cell'.  Therefore, the "is_a" edge between CL:0000457 and CL:0000163 should be removed.

One error that this edge presents is that I can conclude that 'platelet" is part of the 'endocrine system' via the following path: 

CL:0000233 ('platelet') is_a CL:0000458 ('serotonin secreting cell') is_a CL:0000457 ('biogenic amine secreting cell') is_a CL:0000163 ('endocrine cell') part_of UBERON:0002368 ('endocrine gland') part_of UBERON:0000949 ('endocrine system')

I believe this is wrong.

**Comment by cerivs** [comment]
Changed 'biogenic amine secreting cell to be a child of secretory cell.  This should fix the original issue.

**Comment by dosumis** [comment]
We really shouldn't be doing this stuff by hand if we can help it.

If we agree that all cells that are capable of secreting an endocrine hormone are part of the endocrine system, then we should be focussing on recording these capabilities as axioms and relying on the reasoner to classify accordingly.  In this case, can platelets secrete serotonin?  Does the serotonin secreted act as an endocrine hormone.  This should be recorded as an axiom on CL:platelet and backed up by a reference. This is then traceable for future editors.



 Being part of the endocrine system should be based on whether a c

**Comment by cerivs** [comment]
1) Not all biogenic amines are endocrine hormones.
2) The endocrine system is defined as glands and parts of glands  that secrete hormones UBERON:0000949. Thus cells that are not part of glands are not part of the endocrine system.
The CL hierarchy was faulty in this case and we fixed the hierarchy.  

Cells that are parts of an organ  that has  some ancestor endocrine system and are capable of secreting an endocrine hormone are endocrine hormone secreting cells.

Platelets are not part of some endocrine gland thus are not endocrine hormone secreting cells, they are however biogenic amine secreting cell thus biogenic amine secreting cell should not be is_a endocrine hormone secreting cell.

**Comment by dosumis** [comment]
OK.  I understand the logic now.  

> biogenic amine secreting cell should not be is_a endocrine hormone secreting cell.

Yep.  Correct to delete.  It would be nice if we could infer classification under 'secretory cell', but for that we'd need a suitable GO term (which in turn would need a ChEBI term for biogenic amine) so OK to just assert.

> Cells that are parts of an organ that has some ancestor endocrine system and are capable of secreting an endocrine hormone are endocrine hormone secreting cells

That's not what the logical axioms in CL say right now:

endocrine cell
Equivalent to: 'secretory cell' and 'capable of' some 'endocrine hormone secretion'
Subclass of: part of some 'endocrine gland'

This says that ***all*** secretory cell that are capable of endocrine hormone secretion are:
 a type of 'endocrine cell' AND part of an endocrine gland

For the inference you want, you would need the pattern:

endocrine cell EquivalentTo: cell that capable_of 'endocrine hormone secretion' and 'part_of some 'endocrine system'

(don't need secretory cell as this is inferred)

I tried switching, but lots of inferred classification is then lost.  I think it's ok to keep as it is for now.

Note Note: [FBbt](http://www.ebi.ac.uk/ols/ontologies/fbbt/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FFBbt_00007294) deliberately follows the current CL pattern in order to automatically populate the partonomy of the endocrine system (potentially useful for Uberon).

(Rather a lot of verbage to say we don't need to change things, but thought it worth recording once I'd gone to the trouble of working it out).
