### ISSUE TITLE
Question regarding T cell terms

### ISSUE THREAD

**Issue by mbernste** [obophenotype/cell-ontology#505]
Hi, I am attempting to use the Cell Ontology to standardize public metadata (see our project http://metasra.biostat.wisc.edu/) and I am confronting some difficulty in this task when it comes to choosing the correct terms for T cell samples.  More specifically, many existing studies label their T cell data using surface markers (e.g. CD4 or CD8), but do not label their data according to the TCR chain variant (either alpha-beta or gamma-delta).  Most of the T cell terms in the Cell Ontology seem to require that the chain is specified. The main branch under CL:0000084 (T cell) is a subdivision according to the TCR variant.  

Would it make sense to restructure these T cell terms to allow for T cell subsets in which the TCR variant is not specified? Say, for example, to create a term for "CD4-positive T cell" that captures both alpha-beta T cells and gamma-delta T cells that express CD4, since both of these populations of cells exist (see https://www.ncbi.nlm.nih.gov/pmc/articles/PMC4310324/).  I am not a biologist so there may be a very good reason to structure the T cell terms as they are currently structured; however, for the purpose of categorizing existing T cell biological samples, a restructuring of the T cell section of the ontology would be helpful.

Thanks,
Matt

**Comment by addiehl** [comment]
Hi Matt,

Thank you for your interest in and use of the Cell Ontology.  As a major developer of the Cell Ontology and a trained experimental immunologist, I can say that in developing the T cell terms we intentionally avoided creating a literal 'CD4-positive T cell' term because such a term would encompass both CD4+ alpha-beta T cells and CD4+ gamma-delta T cells.  The problem is that immunologists use a lot of short hand in their language, and always mean 'CD4-positive, alpha-beta T cell' when they write 'CD4 T cell' or something similar.  As the paper you have cited mentions, gamma-delta T cells  are a minor subset of peripheral blood T cells (1-10% is the figure given), and CD4+ gamma-delta T cells are <1% of all gamma-delta T cells, thus representing a truly insignificant fraction of all CD4+ T cells in the blood.  For this reason, immunologists always appear to say and assume that CD4+ T cell means 'CD4-positive, alpha-beta T cell' except in the rare situations when they have specifically isolated and studied gamma-delta cells, and the Cell Ontology represents what they actually mean in reality.

I have discussed and confirmed this usage of language and assumed mapping of CD4 T cells to 'CD4-positive, alpha-beta T cell' through conversations with experts immunologists at multiple ontology meetings and workshops devoted to the representation of immunological entities.  I serve on the data standards committee on the Human Immunology Project Consortium, and have discussed this very issue and confirmed that data about CD4 T cells is always assumed to be about CD4+ positive alpha-beta T cells.  The analogous situation exists for CD8+ T cells.  On the other hand, the mapping of CD4 T cell to helper T cell and CD8 T cell to cytotoxic T cell is not at all a strict one as both CD4 and CD8 T cells can exhibit both helper and cytotoxic functions.  Thus we have separate 'helper T cell' and 'cytotoxic T cell' classes with subtypes that include reference to CD4 or CD8 marker expression.

The second reason for not providing a 'CD4-positive T cell' grouping term, apart from its being misleading as described above, is that in T cell development, the choice between alpha-beta and gamma-delta subsets is an absolutely fundamental step and comes before the choice between CD4 and CD8, and indeed CD4 and CD8 expression on gamma-delta T cells is the minority condition in any case, not the binary situation seen in alpha-beta T cells.

In looking at the Cell Ontology, I realize that we have not provided subtypes of 'mature gamma-delta T cell' delineated by CD4 and/or CD8 expression, probably because no one has requested them.  If you need such subtypes for data annotation, please request them.

On the other hand, if your data sources talk about "CD4 T cells" with no reference to isolation of the rare CD4+ gamma-delta subset, you should definitely feel comfortable annotating that data to 'CD4-positive, alpha-beta T cell' as the contribution of the 1/10000 to 1/1000 CD4+ gamma-delta cells to the data and its interpretation is negligible.

Best regards,
Alex

**Comment by mbernste** [comment]
Hi Alex,

Thank you very much for your comprehensive and detailed response. That all makes a lot of sense. I don't have a strong notion for the shorthand used in immunology and therefore have been taking the descriptions of samples very literally.  This answer was very helpful.

Best,
Matt
