### ISSUE TITLE
Problem parsing cl-basic.obo

### ISSUE THREAD

**Issue by balhoff** [obophenotype/cell-ontology#564]
With OWL API in ROBOT and Protege, when I try to load the file downloaded from `http://purl.obolibrary.org/obo/cl/cl-basic.obo`, I get an error:

```
LINENO: 15 - Expected at least one white space at pos: 17
LINE: subsetdef: ro-eco        org.semanticweb.owlapi.oboformat.OBOFormatOWLAPIParser.parse(OBOFormatOWLAPIParser.java:60)
```

**Comment by althonos** [comment]
Same with `fastobo`: the first `subsetdef` clause does not have a declaration, although it is mandatory to have one here.

**Comment by dosumis** [comment]
Apologies.  Had to mung this together for a release as ODK  pipeline was broken  at the time. Thought I'd done a better job than this. 

The problem seems to be failure to retain annotations on ontology during filtering. 

@matentzn  - Do you have -simple & -basic builds working in ODK now?  Does the filter used to  produce them retain ontology level annotations?

**Comment by dosumis** [comment]
Looking at it more closely, looks like I was confused about the OBO ID spec when I added back subsetdefs manually.   I've tested the following for loading in  OBO-Edit. Would everyone be  OK with the following hot fix, rather than  a new release?

```diff
- subsetdef: ro-eco 
- subsetdef: ubprop:upper_level 
+ subsetdef: ro-eco  "eco-subset"
+ subsetdef: ubprop:upper_level "abstract upper-level terms not directly useful for analysis"
```

**Comment by balhoff** [comment]
Sounds good to me.

**Comment by matentzn** [comment]
Is this still a problem?

**Comment by matentzn** [comment]
Thank you @althonos for checking, will close then and we can open new issues for other problems :)
