### ISSUE TITLE
Please review CL:0000477 follicle cell

### ISSUE THREAD

**Issue by paolaroncaglia** [obophenotype/cell-ontology#589]
Please see https://github.com/EBISPOT/efo/issues/599.
Thanks,
Paola

**Comment by nicolevasilevsky** [comment]
This term xrefs FBbt_00004904, which has this text def:
One of the somatic epithelial cells that is either associated with the germline cyst to form an egg chamber or connecting the egg chambers.

@cmungall wrote some comments about this here: https://github.com/obophenotype/uberon/issues/1524

I'm not sure the best way to proceed.

Could we just use the FB text def?

**Comment by paolaroncaglia** [comment]
Pinging @ukemi and @dosumis, please see above and https://github.com/obophenotype/uberon/issues/1524#issuecomment-553664762. Thanks.

**Comment by ukemi** [comment]
PMID:25695427, PMID:31444217, PMID:29497954
These all suggest a relationship, but the fly definition seems much too specific. This is always a tough question.

**Comment by nicolevasilevsky** [comment]
@dosumis suggests renaming this class to 'ovarian follicle cell' and making 'follicle cell' a broad synonym.

**Comment by nicolevasilevsky** [comment]
We talked about this on the CL call today - we renamed the class to 'ovarian follicle cell', added a text def and reclassified it as a child of 'epithelial cell'.

**Comment by paola-scibite** [comment]
Hi, could this ticket be reopened please. I suggest that these two terms are disambiguated, as they're hard to distinguish at first sight unless focusing on the xref and (GO) annotations:

CL:0002174 follicular cell of ovary 
"A cell within the follicle of an ovary."
Has xrefs to FMA and EMAPA, and a link ovarian follicle has part follicular cell of ovary 

CL:0000477 ovarian follicle cell
"A somatic epithelial cell of the ovarian follicle/egg chamber."
Has xref to FBbt, and an editor note "Editors note: check this. Currently used in goxp": the 3 GO terms in which it's used all have manual annotations to Drosophila only.

Could the two terms be added taxon rules to, respectively, exclude and restrict to Diptera? 
And a definition gloss and/or an rdfs:comment added to clarify the above? 
Are there reasons not to add the link 'follicular cell of ovary' part of 'ovarian follicle'?

Thanks,
Paola

**Comment by gouttegd** [comment]
In obophenotype/uberon#1524, @dosumis suggested that the two terms (`follicular cell of ovary` and `ovarian follicle cell`) could be merged as they appeared to be duplicates. It is true that, strictly within CL, the two terms are redundant.

However, I do note that we have in Uberon two distinct terms to refer to the mammalian follicle (`ovarian follicle`, UBERON:0001305) and the insect follicle a.k.a egg chamber (`egg chamber`, UBERON:0003199). While `egg chamber` has been marked as “candidate for obsoletion”, I actually think that it should be retained since `ovarian follicle` is a bit too specific to cover the case of non-mammalian follicles (e.g., it has a `has_part some 'follicular fluid'`, which I don’t think would be correct for insect follicles). And if have two terms in Uberon for the follicles themselves, it kind of makes sense to have two terms as well in CL to refer to the corresponding cells.

Therefore I would agree with @dosumis ’s _other_ suggestion in obophenotype/uberon#1524, which is to rename `ovarian follicle cell` (CL:0000477) to `follicle cell of egg chamber`. Coupled with the taxon rules suggested above (CL:0000477 restricted to _Diptera_ and CL:0002174 excluding _Diptera_), and either a mention in the text definition or a comment, this should help distinguish between the two terms as requested.

(It would then optionally be possible to add a new, more generic term for “follicle cell” encompassing both the mammalian one and the insect one, with the definition suggested (again) by @dosumis: “an epithelial somatic cell associated with a maturing oocyte”, which as far as I know is valid for all follicle cells regardless of species.)

I can take care of implementing this proposal if we agree on it.

**Comment by emquardokus** [comment]
https://rep.bioscientifica.com/view/journals/rep/159/2/REP-18-0593.xml
<img width="787" alt="Screen Shot 2021-12-20 at 1 30 09 PM" src="https://user-images.githubusercontent.com/47257000/146815546-60aa35fe-40db-4037-af7a-0dad620e71da.png">
