### ISSUE TITLE
Question about naive B cells

### ISSUE THREAD

**Issue by bonitalam** [obophenotype/cell-ontology#621]
Hello, we have some biosamples that we believe should be classified as naive B cells (CL:0000788). 

http://purl.obolibrary.org/obo/CL_0000788

Currently, a naive B cell is defined as "a mature B cell that has the phenotype surface IgD-positive, surface IgM-positive, CD20-positive, CD27-negative and that has not yet been activated by antigen in the periphery."

We don't have information on whether the cells are CD20-positive or C27-negative. There is a comment under Term info that says the following:

> This cell type is compatible with the HIPC Lyoplate markers for 'naive B cell'. Per DSD: Naive B cells are also reportedly CD10-negative, CD19-positive, CD20-positive, CD21-positive, CD22-positive, CD25-negative, CD27-negative, CD34-negative, CD40-positive, CD43-negative, CD45-positive, CD48-positive, CD53-positive, CD80-negative, CD81-positive, CD84-positive, CD86-negative, CD95-negative, CD138-negative, CD150-positive, CD184/CXCR4-positive, CD185/CXCR5-positive, CD196/CCR6-positive, CD200-positive, CD229-positive, CD243-positive, CD289-positive, CD290-positive, CD352-positive, MHCII/HLA-DR-positive, cadherin 9-positive, and sIgH-positive, Transcription factors: Pax5-positive, ETS1-positive, FOXO1A-positive, KLF4-positive, KLF9-positive, MiTF-positive, OBF1-positive, PLZF-positive, and SpiB-positive.

This suggests that a naive B cell can be classified for other markers and be considered a naive B cell. We just want to know if it is appropriate to assign this term to our biosamples even we don't know if they are CD20-positive or CD27-negative as stated in the definition.

**Comment by lubianat** [comment]
I am also interested in this question. 

I personally believe that, rigorously, if you have no info on the CD20 / CD27 status, it is not a Cl_0000788 naive B cell. 

It is very likely, though, that it corresponds to the same intended cell type.  This is an instance of the much bigger open problem of how to combine cells that were sorted by different markers into the same cell label. This issue is discussed in [this 2017 paper ](https://www.ncbi.nlm.nih.gov/pmc/articles/PMC5763450/) as an open question. 

Well, I gave my 5 cents. I do not have neither the authority or the know-how  to answer your question, but I am interested in the follow up.

**Comment by addiehl** [comment]
Deciding on whether something is a naive B cell may also depend on your experimental protocol, particularly if you are not sorting by or monitoring marker expression thoroughly because you have already validated your protocol.  But it is true that if you use the Cell Ontology as metadata to describe a biosample, other users of your data might assume all the markers described as being expressed by naive cells are expressed by the cells in your sample, so you should be careful not to over-interpret your data as to which cell types are present if you have any degree of uncertainty.

**Comment by bonitalam** [comment]
Thanks for the input @lubianat and @addiehl

**Comment by nicolevasilevsky** [comment]
Closing, please reopen if you have more questions. thanks!
