### ISSUE TITLE
[NTR] anterior horn cell

### ISSUE THREAD

**Issue by lschriml** [obophenotype/cell-ontology#732]
Note - please check that the term does not already exist (check OLS: https://www.ebi.ac.uk/ols/ontologies/cl)

**Preferred term label:**
anterior horn cell

**Synonyms**

**Definition (free text, please give PubMed ID in format PMID:XXXXXX)**
From NCIT: 
A motor neuron that is located in one of the ventral horns of the spinal cord and innervates skeletal muscles of the trunk or head

**Parent cell type term (check the hierarchy here https://www.ebi.ac.uk/ols/ontologies/cl):**

**What is the anatomical structure that the cell is a part of? Please check Uberon: https://www.ebi.ac.uk/ols/ontologies/uberon**

**Your nano-attribution (ORCID)**

**Any additional notes or concerns**

NCIT_C12645

**Comment by nicolevasilevsky** [comment]
Note: anterior horn cell is a narrow synonym for CL_0000100 'motor neuron'.

Motor neuron should be the parent class for this new term. 

See synonyms in NCIT: https://www.ebi.ac.uk/ols/ontologies/ncit/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FNCIT_C12645

**Comment by addiehl** [comment]
ventral horn of spinal cord
http://purl.obolibrary.org/obo/UBERON_0002257

**Comment by addiehl** [comment]
Maybe David can comment on how to capture the innervation part of the text definition.

**Comment by nicolevasilevsky** [comment]
^ @dosumis

**Comment by dosumis** [comment]
I think this corresponds to: 
[ventral horn of spinal cord spinal cord motor neuron](https://www.ebi.ac.uk/ols/ontologies/cl/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FCL_2000048&viewMode=All&siblings=false)

The name is horrible and ungainly, so I suggest changing to 'anterior horn cell'.  The definition can be 
based on https://www.sciencedirect.com/topics/medicine-and-dentistry/anterior-horn-cell + https://en.wikipedia.org/wiki/Alpha_motor_neuron  (can be added as new parent class, but that shouldn't hold up changes requested here

Instead of part_of to uberon we should have:

has_soma_location some 'ventral horn of spinal cord'
For muscle relationship, this will do for now:
synapsed_to some 'skeletal muscle'

But this can be improved with improvement to the motor neuron hierarchy: I think we need a small, focussed project to fix the motor neuron hierarchy.  It's a bit of a mess right now - https://github.com/obophenotype/cell-ontology/projects/9
