### ISSUE TITLE
[Logical def] Tighten up definition of Betz cell to restrict to layer 5?

### ISSUE THREAD

**Issue by dosumis** [obophenotype/cell-ontology#778]
**CL term**

Betz cell CL_0008049

(Note - at time of writing - term is in pull request https://github.com/obophenotype/cell-ontology/pull/767

**Suggested revision of logical definition**

Paola notes in https://github.com/obophenotype/cell-ontology/pull/767#issuecomment-702786745 :

> @dosumis 
> If I'm reading [this diff](https://github.com/obophenotype/cell-ontology/pull/767/commits/fb0ab35195a2999bedd27b70f72e0da4906e3cf0) right, you made 'Betz cell' a part of 'primary motor cortex'. Based on [this ref](https://www.ncbi.nlm.nih.gov/books/NBK10962/) ("The pyramidal cells of cortical layer V (also called Betz cells) are the upper motor neurons of the primary motor cortex"), we could even be more specific and 
> - [ ] Link 'Betz cell' to UBERON:0022315 'primary motor cortex layer 5' (instead of 'primary motor cortex')? 
> 
> Also confirmed by [this ref](https://www.ncbi.nlm.nih.gov/books/NBK554616/) ("In the primary motor cortex are the cell bodies of the upper motor neurons, referred to as Betz cells. Specifically, these cells are located in layer 5 of the motor cortex and have long apical dendrites that branch up into layer 1.") and by [this Wikipedia entry](https://en.wikipedia.org/w/index.php?title=Betz_cell&oldid=977472330) ("Betz cells (also known as pyramidal cells of Betz) are giant pyramidal cells (neurons) located within the fifth layer of the grey matter in the primary motor cortex.").
> That is, if my understanding is correct that for neurons with potentially long processes, the part_of axiom indicates where the body of the cell is found (not where it synapses). Please correct me if that's not the case. Cheers!
> (Update: ok I've read the documentation [here](https://github.com/obophenotype/cell-ontology/blob/draft_relations_doc/documentation/relations_guide.md) now re. neurons)
> 

The case for this looks very strong, but I'd like to check that this applies sufficiently across species before adding.   I think this is part of a more general discussion we need to the Brain Data Standards project

Questions:
1. Is the term Betz cell used across mammals?  More widely?
2. Is the layer structure/numbering sufficiently conserved across mammals that recording a (soma) location to layer 5 makes sense across species?
3. How much is known about soma location of Betz cells in mammals?

@jeremymiller @BAevermann @tgbugs - do you have the background knowledge needed to make a suggestion on this?  If not, could you suggest someone who could comment?  (Was thinking of asking Amy Bernard, but not sure she's on GitHub).

**Comment by tgbugs** [comment]
1. Yes. Not sure, but I think the terminology is specific to mammals, I've never see it used elsewhere.
2. The 6 layer convention is a convention, and some anatomists would tell you that it is a major oversimplification, with the actual number varying across areas in the same individual, and across species in the same area. However, in most cases the cell populations are conserved enough that some mapping to 6 layers can be accomplished. Layer numbering within motor cortex is somewhat simplified by the presence of Betz cells, because they usually define layer 5b. Also, the size of the soma makes it less of an issue because they are so much lager than other nearby pyramidal neurons.
3. Quite a bit, though part of the issue is that practically the layer they are in may be defined by their presence, not the other way around.

I did my 2nd rotation project (a while ago now) collecting RNA from single Betz cells in rat, so I'm somewhat familiar.

One thing I can say for sure is that there are significant disagreements (last I checked) about the projection targets of these cells in rodents vs in primates, and even within primates. Specifically
around whether they are targeting motor neurons directly (exactly which they are targeting in human vs macaque), or whether they are targeting interneurons in the spinal cord. Those distinctions will likely be subclasses.

Trygve Bakken at Allen is likely to be the one with the most knowledge of what is going with the Betz cells at a molecular level (they do not have a consistent molecular signature), and across mammalia. https://www.biorxiv.org/content/10.1101/2020.03.31.016972v2.

**Comment by jeremymiller** [comment]
A whole lot is known about Betz cells and it's an area of active research at the institute.  If you are looking for a contact about this at the Allen Institute (who also has a GitHub account), then Trygve (@tebakken on GitHub) is a great choice.  In short, we are confident that they are long-range projection neurons in layer 5 (which we call "L5 extratelencephalic (ET)" aka "L5 pyramidal tract (PT)" aka "L5 corticofugal (CF)").  I _think_ these are thought to be so big because the project all the way to the spinal cord, but please confirm that.  There are homologous cell types that are well preserved based on gene expression in mouse and primate, but I'm pretty sure that anatomically-defined Betz cell (e.g., gigantocellular cells) are not found in mouse.

**Comment by paolaroncaglia** [comment]
@tgbugs @jeremymiller cc @dosumis 
Thank you very much for your expert feedback!
While we wait in case @tebakken kindly has a chance to comment, I'll summarize my understanding of how @dosumis and I should translate this into the Cell Ontology:
- [ ] Restrict 'Betz cell' to Mammalia
- [ ] Keep the location axiom broader, to 'primary motor cortex'
- [ ] Relax and gloss the definition, from "A giant pyramidal neuron with a soma in the primary motor cortex that functions as an upper motor neuron, sending their axons down the spinal cord via the corticospinal tract." to "A pyramidal neuron with a soma in the primary motor cortex that functions as an upper motor neuron, sending its axons down the spinal cord via the corticospinal tract. In humans, Betz cells are the largest known in the central nervous system, and their soma are located in layer Vb of the primary motor cortex."

Also, quick note for self,
- [ ] Check if the UBERON:0022315 'primary motor cortex layer 5' needs synonyms (cfr. Jeremy's note "...layer 5 (which we call "L5 extratelencephalic (ET)" aka "L5 pyramidal tract (PT)" aka "L5 corticofugal (CF)")").

**Comment by dosumis** [comment]
From @tebakken's paper  (https://www.biorxiv.org/content/10.1101/2020.03.31.016972v1.full.pdf):

> L5 of carnivore and primate M1 contains exceptionally large “giganto-cellular” corticospinal neurons (Betz cells in primates 15,16 that contribute to the pyramidal tract and are highly specialized for their unusually large size with distinctive “taproot”-style dendrites 17,18. Extracellular recordings from macaque corticospinal neurons reveal distinctive action potential properties supportive of a high conduction velocity and similar, unique properties have been reported during intracellular recordings from giganto-cellular neurons in cats19–21. Additionally, some primate Betz  cells directly synapse onto alpha motor neurons, whereas in cats and rodents these neurons synapse instead onto spinal interneurons 22,23. These observations suggest that Betz cells possess specialized intrinsic mechanisms to support rapid communication, some of which are primate specific.

1. I think reasonable to restrict to layer5 (given that it is layer defining) - we might further tighten up to 5b at a later point (requires term import from Uberon)
2. We should use the looser 'present in taxon' relation (AP) to record presence in primates.  TBD: restict the name 'Betz' to the primates or allow for carnivora.  It seems reasonable *not* to use this term more broadly in the mammalia, but to come up with a more general 
3. Connectivity issue.  We currently have  Betz (in the Pull Request) as a type of 'upper motor neuron', which is defined as: "A glutamatergic motor neuron with a soma in the brainstem or cerebral cortex.  They do not synapse directly to muscles but rather to lower motor neurons, which do." .  However, it sounds from the Baaken text and from Tom's comments that this connectivity applies to only some Betz cells in primates, so only a subclass would count as 'upper motor neurons'.

**Comment by shawntanzk** [comment]
Might redo the terms as when trying update from master, theres a huge amounts of clashes that would probably be more difficult to untangle than to do redo

1. will import the term from Uberon (http://purl.obolibrary.org/obo/UBERON_0022315) and use 'has soma location' in layer 5 of primary motor cortex
2. will import 'present in taxon' from RO (http://purl.obolibrary.org/obo/RO_0002175) and primates (NCBITaxon:9443), and put Betz cell as subclass of 'present in taxon' some 'primates'
3. we can leave it asserted under pyramidal neuron, and remove subclass of upper motor neuron and instead have 'syanpse to' some 'lower motor neuron'? Happy to still add upper motor neuron (which only exists in the pull request at the moment)

**Comment by dosumis** [comment]
I already merged from master with no problems.  Realised I forgot to push (have done now). You should [re-serialise](https://github.com/obophenotype/cell-ontology/blob/master/docs/resolving_merge_conflicts.md) master before you merge - there were quite a lot of changes that were just ordering

**Comment by shawntanzk** [comment]
From the discussion above, and @tebakken's paper, perhaps this for the def?  
"A pyramidal neuron with a soma in layer Vb of the primary motor cortex that functions as an upper motor neuron, sending its axons down the spinal cord via the corticospinal tract, synapsing directly with alpha motor neurons, or targeting interneurons in the spinal cord. In humans, Betz cells are the largest known in the central nervous system." 

Also will remove subclass of synapsed_to some lower_motor_neuron as this doesn't include Betz cells that synapse to spinal cord interneurons. I'm guessing we then have subclasses for species that specify that?

**Comment by tgbugs** [comment]
I seem to recall that there was some disagreement about the exact targets of the Betz cells in different species, especially with regard to whether they were directly projecting onto motor neurons or whether they were targeting other interneurons. IIRC The disagreement surfaced between non-human primate and human. Maybe it has been resolved now in favor of the direct projection?

**Comment by shawntanzk** [comment]
From @tebakken's paper: 

> Additionally, some primate Betz cells directly synapse onto alpha motor neurons, whereas in cats and rodents these neurons synapse instead onto spinal interneurons

so I'm guessing the use of the word "some" indicates that disagreement?

**Comment by dosumis** [comment]
Upper neuron def currently specifies direct synapsing on to lower motor neurons, so if this stays, Betz cell can't be a subclass, but we could add a Betz upper motor neuron class for the ones that do - using present_in_taxon AP to Human to record that this has been confirmed as present in humans.

**Comment by shawntanzk** [comment]
I'll remove "functions as an upper motor neuron" from def (was hoping the "functions as" would be ok with upper motor neuron, but I guess with upper motor neuron def, that wouldn't work still). 
Can make a Betz upper motor neuron subclass under Betz cell that has present_in_taxon with humans

**Comment by shawntanzk** [comment]
Merged #767
