### ISSUE TITLE
[NTR]: mantle zone B cell

### ISSUE THREAD

**Issue by ngeorgeebi** [obophenotype/cell-ontology#903]
Note - please check that the term does not already exist (check OLS: https://www.ebi.ac.uk/ols/ontologies/cl)

**Preferred term label:**
mantle zone B cell

**Synonyms**
lymph node mantle zone B cell; mantle zone B cell of lymph node

**Definition (free text, please give PubMed ID in format PMID:XXXXXX)**
A B lymphocyte that resides in the mantle zone of the lymph node germinal center. These are generally IgM and IgD positive activated B cells that form a 'corona' around the germinal center and are part of the establishment of a secondary lymphatic follicule. https://www.arppress.org/v/vspfiles/assets/images/Chapter1T25LymphNodes.pdf

**Parent cell type term (check the hierarchy here https://www.ebi.ac.uk/ols/ontologies/cl):**
germinal center B cell: http://purl.obolibrary.org/obo/CL_0000844

**What is the anatomical structure that the cell is a part of? Please check Uberon: https://www.ebi.ac.uk/ols/ontologies/uberon**
lymph node germinal center mantle zone:  (NTR: https://github.com/obophenotype/uberon/issues/1762) AND lymph node: http://purl.obolibrary.org/obo/UBERON_0000029

**Your nano-attribution (ORCID)**
orcid.org/0000-0003-4183-8865/

**Any additional notes or concerns**
Can we add part of lymph node to germinal center B cell? @paolaroncaglia

**Comment by ngeorgeebi** [comment]
@paolaroncaglia I haven't finished the definition yet. Will work on it Monday

**Comment by paolaroncaglia** [comment]
Note for self: depends on https://github.com/obophenotype/uberon/issues/1762.

**Comment by addiehl** [comment]
A nice older review article on lymph node germinal center structure is [PMID:8011279](https://pubmed.ncbi.nlm.nih.gov/8011279/) and should be used in addition to the book chapter which does not come with proper citation details (ie, the URL could go dead without warning, although it is a nice chapter).

I think the primary term label should be 'lymph node mantle zone B cell'.  We have to keep in mind that both the spleen and tonsils have germinal centers with mantle zones, and this term should be specific for this cell type in the lymph node.

per comments in #1762, this cell type should be 'part of' some 'lymph node follicular corona'

Also, addressing Paola comment, because germinal center B cells occur in spleen and tonsil as well as lymph node, we should not make 'germinal center B cell' part of 'lymph node'.  If you want to create a lymph node specific subclass, that could be part of the 'lymph node'.
-- Alex

**Comment by paolaroncaglia** [comment]
Note to self, this will be easier to address when Uberon is released, as it'll have updates around mantle zone terms.

**Comment by paolaroncaglia** [comment]
Hi @ngeorgeebi (cc @sfexova ),

The new term is CL_0009037 (lymph node mantle zone B cell).
It will be available with the next CL release, but I'm not sure when that will be. The last release was on August 10th, so when I've finished adding the remaining CL terms for SCA (hopefully next week), I could ask for a new CL release.

Best,
Paola
