### ISSUE TITLE
[Synonym]: marginal zone B cell of lymph node

### ISSUE THREAD

**Issue by ngeorgeebi** [obophenotype/cell-ontology#975]
Note - please check that the term does not already exist (check OLS: https://www.ebi.ac.uk/ols/ontologies/cl)

**Preferred term label:**
marginal zone B cell

**Synonyms**
lymph node marginal zone B cell

**Definition (free text, please give PubMed ID in format PMID:XXXXXX)**
A B cell that resides in the lymph node marginal zone. Marginal zone B cells (MZ B cells) are noncirculating mature B cells that in humans segregate anatomically into the marginal zone (MZ) of the spleen[1] and certain other types of lymphoid tissue.[2] The MZ B cells within this region typically express low-affinity polyreactive B-cell receptors (BCR), high levels of IgM, Toll-like receptors (TLRs), CD21, CD1, CD9, CD27 with low to negligible levels of secreted-IgD, CD23, CD5, and CD11b that help to distinguish them phenotypically from follicular (FO) B cells and B1 B cells. https://en.wikipedia.org/wiki/Marginal_zone_B-cell

**Parent cell type term (check the hierarchy here https://www.ebi.ac.uk/ols/ontologies/cl):**
mature B cell http://purl.obolibrary.org/obo/CL_0000785

**What is the anatomical structure that the cell is a part of? Please check Uberon: https://www.ebi.ac.uk/ols/ontologies/uberon**
lymph node marginal zone (needs NTR - separate to lymph node follicular corona)

**Your nano-attribution (ORCID)**
0000-0003-4183-8865

**Any additional notes or concerns**

**Comment by ngeorgeebi** [comment]
@paolaroncaglia could you please tag with SCA
So the definition of this is the same as that used for mantle zone B cell - but it is located in the lymph node rather than the spleen - so didn't feel right making it a synonym. Whats the best way to go about this?
Additionally the follicular corona of the germinal center is made up of the mantle zone and the marginal zone of the germinal center. So I have assumed follicular corona to mean 'mantle zone of lymph node secondary follicule' and will make marginal zone of germinal center as a sep term. Would this work?
Thanks!
Nancy

**Comment by paolaroncaglia** [comment]
This will be easier/clearer to address when Uberon is released and ingested.

**Comment by paolaroncaglia** [comment]
Update/notes for self:
- [ ] Depends on https://github.com/obophenotype/uberon/issues/1767
- [ ] UBERON:8410065 'lymph node follicle marginal zone' has been released by Uberon, but not imported into CL yet
- [ ] The existing term CL:0000845 'marginal zone B cell' is defined (textually and logically) as being part of 'marginal zone of spleen'; look into disambiguating its label to 'marginal zone B cell of spleen', and see if any of its exact synonyms need to be made broad instead.

**Comment by paolaroncaglia** [comment]
@addiehl 
The existing term CL:0000845 'marginal zone B cell' is defined (textually and logically) as being part of 'marginal zone of spleen'. In order to disambiguate, could you please let me know if you have any objection with the following suggestions (I can make the edits):
- [ ] rename as 'marginal zone of spleen B cell' 
- [ ] add exact syn 'B cell of marginal zone of spleen'
- [ ] keep 'marginal zone B cell' as a broad syn
- [ ] all previously existing exact syns: change scope to broad

Thanks,
Paola

**Comment by addiehl** [comment]
I would prefer CL:0000845 to be renamed 'marginal zone B cell of spleen', in order to preserve the wide used name 'marginal zone B cell' as a continuous part of the name.  Marginal zone B cells in the spleen are a very well studied type of B cell and when the name "marginal zone B cell" is encountered in the immunological literature, it is most commonly referring to the MZ B cell of the spleen.

I agree with the synonym changes for CL:0000845 and I think 'marginal zone of spleen B cell' can be made an exact synonym.

And a separate term should be created for 'marginal zone B cell of lymph node', as a sibling of CL:0000845 under 'mature B cell'.  At this point, I would avoid a grouping term since I am not sure if the two cell types are similar enough to warrant that.  And a simpler definition, such as "A mature B cell located in the marginal zone of the lymph node" should be used.

**Comment by paolaroncaglia** [comment]
Thanks @addiehl .

**Comment by paolaroncaglia** [comment]
@ngeorgeebi @sfexova 
The new term is CL:0009060 marginal zone B cell of lymph node.

@addiehl 
CL:0000845 has been edited as agreed. Thanks.
