### ISSUE TITLE
[Class hierarchy]: plasma cell

### ISSUE THREAD

**Issue by ngeorgeebi** [obophenotype/cell-ontology#990]
**CL term**
plasma cell: http://purl.obolibrary.org/obo/CL_0000786

**Suggested revision and reasons**
Please can we include the part of lymph node tag. Although the description mentions the spleen specifically. Should I make a plasma cell of lymph node instead?
Requested for SCA

**Comment by addiehl** [comment]
Please do not make plasma cells part of spleen or lymphonode.  Plasma cells can be found in a wide variety of tissues and organs in the body.

Please understand that when you assert a cell type is 'part of' some anatomical structure, you are saying all instances of that cell type are always found in that anatomical structure.  If this is true, you can make statements like hepatocyte part of some liver.  If it is not true, do not make the assertion.  It is necessary for the Cell Ontology to omit anatomical localization for many immune cell types because these cell types move around the body as part of their normal lifecycle and functioning.

Alex

**Comment by dosumis** [comment]
>  Should I make a plasma cell of lymph node instead?

Yes please
